### ISSUE TITLE
IE fails to parse data:image/svg+xml;base64

### ISSUE THREAD

**Issue by postc0de** [exupero/saveSvgAsPng#1]
IE fails to parse xml image:
XML5661: Non-default namespace declarations must not have an empty URI. Line: 1, Column 335

Checked on latest IE11, but earlier versions are affected too.

**Comment by exupero** [comment]
I think you'll have other problems trying to save PNGs from canvases in IE 11, since last I checked `canvas.toDataURL()` is considered a security error.

**Comment by stryju** [comment]
i have to disagree here - there are some other quirks with IE in general, but basic conversion is done right

**Comment by exupero** [comment]
I'm no expert in IE, so perhaps I have something misconfigured, but trying to save PNGs from IE 11 gives me a SecurityError at `canvas.toDataURL()`, both when saving an SVG loaded by the user and saving an SVG that's inline in the HTML (I'm using [this test page](http://exupero.org/saveSvgAsPng/)).

Are you doing something different such that it works in IE?

**Comment by exupero** [comment]
I'm also using Windows 8 to test. Perhaps it works in Windows 7?

**Comment by stryju** [comment]
will check, when i get the chance and will report with results ;-)
