### ISSUE TITLE
Issue in Safari

### ISSUE THREAD

**Issue by ctants** [exupero/saveSvgAsPng#100]
I didn't see it noted anywhere, but in Safari (all versions), instead of downloading the png it loads it in the browser window. Is this a known issue? Is there any workaround for this?

**Comment by sheriferson** [comment]
Yes, it seems to be an unfortunate stable problem with Safari - see #37.

**Comment by ctants** [comment]
ok, bad Safari! Is it possible to open the png at least in an new tab?
I've added
`a.target = "_blank";`
 to line 259 but it has no effect.

**Comment by exupero** [comment]
Closing as duplicate of #37.
