### ISSUE TITLE
styles being ignored

### ISSUE THREAD

**Issue by Jephuff** [exupero/saveSvgAsPng#108]
the external styles are being ignore in the export: https://jsfiddle.net/4gn8zjqu/3/

From what I can tell, it started after this line in this commit:
https://github.com/exupero/saveSvgAsPng/commit/f56023bcca4f338dcdc54aea273e688b9478c6db#diff-6e9b9354fd4b408541c24dc0237e9502L201
switching `var svg = doctype + outer.innerHTML;` to `var svg = doctype + new XMLSerializer().serializeToString(clone);` seems to break the `<![CDATA[]]>` causing it to ignore the styles. 

In some local tests I was able to fix it by either reverting that change, or removing the CDATA wrapper from this line `s.innerHTML = "<![CDATA[\n" + css + "\n]]>";`

I can make a pull request for one of those changes, but didn't want to cause any regression.

**Comment by exupero** [comment]
I'm fine with reverting the change.

**Comment by Jephuff** [comment]
Sounds good, I will make a pull request.
