### ISSUE TITLE
Styles ignored for the root <svg> node

### ISSUE THREAD

**Issue by ravilov** [exupero/saveSvgAsPng#110]
I had some styles applied directly to the root `<svg>` node (namely background color) but they were getting ignored when attempting to generate the PNG. I created a patch to fix this issue:

[saveSvgAsPng.js.diff](https://github.com/exupero/saveSvgAsPng/files/551391/saveSvgAsPng.js.diff.txt)

**Explanation:** `Node.querySelector()` only inspects the subnodes and will not return the node itself, even when it matches the given selector. The fix involves using the node's parent instead.

_Example:_ For `<svg class="chart" id="chart" />`, `document.getElementById('chart').querySelector('svg.chart')` will return `null`. This is true at least for Firefox 45.3.0 running on Debian/x86_64.

**Comment by exupero** [comment]
There's currently a CSS selector rewrite option that you may find useful. It was added to help with a superset of the problem you describe, specifically having CSS selectors that select elements higher in the DOM than the SVG's children.

I'm not opposed to this change, but I'm not certain it's needed, at least not in a wide-enough variety of cases. I'm open to hearing others' thoughts on whether this is useful and whether or not it will break any existing patterns in how people are using this library.

If you would, please convert this issue to a pull request with the changes you propose so it's easier for others to check them out.

**Comment by broncha** [comment]
@exupero selectorRemap and modifyStyle are only called if `match = el.querySelector(selectorText);` is true, which in this case is always false.

**Comment by exupero** [comment]
Check out #137 and tell me if that would solve the problem.

**Comment by broncha** [comment]
It would yes.

**Comment by exupero** [comment]
Merged. Re-open if it's still a problem.
