### ISSUE TITLE
Css rule for fill:"option" doesn't seem to apply

### ISSUE THREAD

**Issue by avdept** [exupero/saveSvgAsPng#113]
I have svg element with `fill: none`, which is not being handled correctly. Did i miss anything?
![diagram 9](https://cloud.githubusercontent.com/assets/1757017/19892596/4fde5c3a-a04e-11e6-87e1-c2c0a9ed2a11.png)

PS: Update - this rule applied via class name

**Comment by exupero** [comment]
Could be a problem with the specificity of the CSS selector.

**Comment by avdept** [comment]
How can i debug\fix it?

**Comment by exupero** [comment]
You could try giving the path an ID and styling that directly. Other than that, I'd need to see a minimal reproduction.

**Comment by avdept** [comment]
This is jointJS tool, if you need example.

**Comment by avdept** [comment]
Added fixes for my specific case, so closing it now.

**Comment by pavodev** [comment]
May I ask how did you solve this problem? I'm getting the same behavior with d3.js. Whenever i export my chart, the svg fill images disappear..
