### ISSUE TITLE
in chrome, download doesnt happen for more than 1.3MB png file

### ISSUE THREAD

**Issue by may16197** [exupero/saveSvgAsPng#115]
Hi,
I am using saveSvgAsPng.js to save my svg as png.In chrome, i am not able to download png file more than 1.3MB . I have close to 500 nodes and the download to png file is close to 1.6MB and its throwing error in chrome. But works fine in FF.

I have tried to use the scale option and it doesnt help. When the zoom level on my svg is 60%, download happens on chrome. above that it throws network error.

Thanks,
DD

**Comment by exupero** [comment]
I don't know of anything we can do about network errors. If you have any information to the contrary, feel free to reopen.

**Comment by may16197** [comment]
Thanks..I have tried with  scale: 0.7 option to reduce the file size and it works fine till I use scale:07, if i use use above this, it breaks..
