### ISSUE TITLE
how to use canvg option?

### ISSUE THREAD

**Issue by may16197** [exupero/saveSvgAsPng#116]

**Comment by exupero** [comment]
My understanding is that you should pass a function, likely one provided by canvg, though you'd have to ask @Jephuff to be certain.

**Comment by Jephuff** [comment]
thats right, take a look at https://github.com/canvg/canvg for usage instructions. If you load canvg through the script tags, then you can just pass `window.canvg` into saveSvgAsPng.

``` js
svgAsPngUri(document.getElementById("diagram"), {canvg: window.canvg}, function(uri) {
  ...
});
```
