### ISSUE TITLE
even afetr using canvg, i am not able to download as png in IE11

### ISSUE THREAD

**Issue by may16197** [exupero/saveSvgAsPng#117]
Hi,
i am trying to use this on IE10 and i am getting below error "Rendered SVG images cannot be downloaded in this browser.". Which IE version this canvg option works?

I am using canvg as below:
var canvas =  document.querySelector("canvas"); 
			var svg = document.querySelector('svg');
        saveSvgAsPng(svg, "topo_diagram.png",{canvg:window.canvg(canvas,svg)} );

this works fine in firefox..

any help on this is greatly approciated.

regds,
DD

**Comment by exupero** [comment]
I'll direct the question to @Jephuff as I've not used canvg.

**Comment by Jephuff** [comment]
saveSvgAsPng will call canvg directly, so all you need to pass is a reference to the function. Try this

```
var svg = document.querySelector('svg');
saveSvgAsPng(svg, "topo_diagram.png",{canvg:window.canvg} );
```

**Comment by may16197** [comment]
Hi Jephuff ,

Thanks for replying. I have tried whatever you have mentioned .Still it doesnt work.IE stops responding

The recent saveSvgAsPng.js doesnt work in any browser. 

regds,
DD

**Comment by Jephuff** [comment]
If you can reproduce in a jsfiddle I can take a look.

**Comment by may16197** [comment]
Hi Jephuff,

here my file in jsfiddle..
https://jsfiddle.net/asew/ja9bxz2r/4/

I am not too familiar with jsfiddle. So i am not sure how it will pick external resources. I have mentioned them in external resources.

thanks,
DD

**Comment by Jephuff** [comment]
For the external resources just get the links to the files on a cdn. 

d3 provides a link on there home page (looks like your using v3 though, so change v4 to v3 in the url.)
canvg provides the links on their github page (change them to https) and for anything else like, saveSvgAsPng, grab a link to the raw asset on github and change `raw.githubusercontent` to `rawgithub`

Once you the svg rendering, send the updated fiddle over :) (I'd recommending testing the link in an incognito window first, just to ensure you don't have any unsaved changes)

**Comment by may16197** [comment]
somehow , in jsfiddle the svg is not loading..let me try it once more.

for me, the recent saveSvgAsPng.js is not wrking at all in anybrowser even if i do not use canvg option. If i switch to old js file, it works for chrome and FF.

does the size of SVG matters? I have around 500+ nodes and links

when i tried to debug with both old and new js files, I found out that new saveSvgAsPng,js keeps on looping and never comes out and hence no download. I dnt know whether its relevent.

**Comment by exupero** [comment]
It sounds like you may have a problem with your SVG. Does the developer console log anything when you try to download? It's possible the SVG is invalid.

**Comment by may16197** [comment]
Thanks for the reply and  patience. 


my function:
function download(){
var svg=document.querySelector("svg") 
saveSvgAsPng(svg,"topo.png",{canvg:window.canvg} );
}


wow...atlast i could find out the problem...The problem was my function had download() name and js file too has download function .


Now the file is getting downloaded, but if i use canvg option, i get empty png file...the same issue with all browsers.

but in my application,on IE, it throws "Rendered SVG images cannot be downloaded in this browser"

plz help!!


thanks,
DD

**Comment by Jephuff** [comment]
That error sounds like either `window.canvg` is `undefined` or it's an older version of `saveSvgAsPng`.
Could you confirm that canvg is being loaded properly? (set a breakpoint on this line `saveSvgAsPng(svg,"topo.png",{canvg:window.canvg} );` and check the value
And also confirm you have the latest version of saveSvgAsPng (you could always search the source for it for any reference to `canvg`)

**Comment by may16197** [comment]
Hi,

window.canvg is not 'undefined' and I am using newst version of saveSvgAsPng., when I debug, everything looks fine and no erros as well. But the downloaded file is empty. I could see canvg file being referenced , everythign flows smoothly. Not able to understand the issue.



thanks,
DD

**Comment by may16197** [comment]
Hi,

Any other way to export SVG to PNG in IE.

regds,
Deepa


i tried to use canvg directly and used this program. Still this returns empty png file

var svg;
function generateLink(fileName, data) {
      var link = document.createElement('a');
      link.download = fileName;
      link.href = data;
      return link;
    }
    
    function SVG2PNG(svg, callback) {
      var canvas = document.createElement('canvas');
      var ctx = canvas.getContext('2d');
      var data = svg.outerHTML;
      canvg(canvas, svg);
      callback(canvas);
    }
	
	d3.select("#download").on("click", function(){
		svg = document.querySelector('svg');
		  //saveSvgAsPng(svg, "topo_diagram.png",{canvg:window.canvg,scale:0.5} );
		  SVG2PNG(svg, function(canvas) {
				var base64 = canvas.toDataURL("image/png");
				generateLink('topo.png', base64).click();
			  });
});

**Comment by may16197** [comment]
Hi Jephuff,

when i changed the code in saveSvgAsPng.js at line num 250 to this..

if(options.canvg) {
				options.canvg(canvas, src,{
					ignoreMouse : true,
					ignoreAnimation : true,
					renderCallback : function(){ cb( png,canvas ); }
				});


the PNG file is loaded with nodes and images. But CSS is not applied.
Any hint would be highly appriciated.

regds,
DD

**Comment by Jephuff** [comment]
I would need a fiddle figure out whats going on with the styles.
Probably I should have added the `ignoreMouse: true` and`ignoreAnimation: true` options.
