### ISSUE TITLE
image.onload does not work in iphone6s

### ISSUE THREAD

**Issue by guaizi149** [exupero/saveSvgAsPng#120]
`    out$.svgAsDataUri(el, options, function(uri) {
        var image = new Image();

        **image.onload** = function() {
          convertToPng(image, image.width, image.height);
        }

        image.onerror = function() {
          _log("block");
          console.error(
            'There was an error loading the data URI as an image on the following SVG\n',
            window.atob(uri.slice(26)), '\n',
            "Open the following link to see browser's diagnosis\n",
            uri);
        }
        image.src = uri;
      });
    }
  }`

**Comment by guaizi149** [comment]
by the way,it works perfectly in pc(like chrome ,ff,opera). _log() is a function to output the message to a div.
when in mobile, image.onerror is triggered. and no png.

**Comment by exupero** [comment]
I'd take a PR to conditionally set `image.onerror`. I don't personally have a way to test this.

Is there an alternative way to catch errors and log them for platforms without `image.onerror`?

Also, what happens on the iPhone when the lib tries to download? Does it go into saved images, or does it just show a PNG in the browser?

**Comment by langlong149** [comment]
Here is HTML:
`    <div class="svgBox">            
        <img src="" class="svg-img" />
        <div id="log_box"></div>
    <button class="back">返回</button>     
    </div>`
JS：
`        download1.addEventListener("click",function(){
                svgBox.style.display = 'block';
                svgAsPngUri(graph_box, {}, function(uri) {
                    svgImg.setAttribute("src",uri);
                 });
            }); 
            window.onerror = function(message, source, lineno, colno, error) { 
            error1.innerHTML = message + source + lineno + colno + error;
         }

         window._log = function (str){
            var logbox = $("#log_box");
            $('#log_box').html($('#log_box').html() + "<br/>" + str);
         }`
just show a PNG in the browser.
i tried window.onerror,but it doesnot work.

**Comment by langlong149** [comment]
![qq 20161122123324](https://cloud.githubusercontent.com/assets/19711638/20511123/71e11116-b0b0-11e6-8c95-10f45cbd3651.png)
![qq 20161122123436](https://cloud.githubusercontent.com/assets/19711638/20511128/7ac8ca08-b0b0-11e6-82f4-a436f6ac6994.jpg)
uri can be read.

**Comment by langlong149** [comment]
![qq 20161122123400](https://cloud.githubusercontent.com/assets/19711638/20511140/9f535f96-b0b0-11e6-850d-35c38129b5cb.png)
![qq 20161122123406](https://cloud.githubusercontent.com/assets/19711638/20511144/a679bd10-b0b0-11e6-8e32-aadf775f50de.png)
when _log("block") in the image.onload, it doesn't work. when beyond the function, it works.
![img_2300](https://cloud.githubusercontent.com/assets/19711638/20511228/578a29a0-b0b1-11e6-9efc-7c984544be80.PNG)

**Comment by guaizi149** [comment]
i have found why this happen:
it doesn't work in safari,whether in pc or mobile. it work perfectly in andriod mobile.
it is because the `<use>` in svg.
in other browser,use behave as follows:
`<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#link_id0_5292783"></use>`
but in safari:
`<use NS1:href="#link_id0_9505622"></use>`

**Comment by guaizi149** [comment]
i already pulled a request to fix this.
