### ISSUE TITLE
saved PNG in browser is highly clear but on server side then it's not

### ISSUE THREAD

**Issue by andy2046** [exupero/saveSvgAsPng#124]
hi eric,

my question is 

saved PNG in browser is highly clear but when i send it back to server then the PNG is blur, how can I solve this issue? thanks

**Comment by exupero** [comment]
I need more details about exactly what you're doing. If it's being downloaded fine, odds are that the problem is in whatever process is uploading it to the server, which this library would not have any part in.

**Comment by f0ff886f** [comment]
Make sure you're not running into this problem:

https://stackoverflow.com/questions/24395076/canvas-generated-by-canvg-is-blurry-on-retina-screen

I'm fighting with it now, will hopefully have a fix soon.

**Comment by exupero** [comment]
You should be able to fix that problem with the `scale` option. Saving a scaled up version of the image and displaying within the original dimensions will provide a sharper image.
