### ISSUE TITLE
 not working in Safari 10.0.1

### ISSUE THREAD

**Issue by ziinfo** [exupero/saveSvgAsPng#125]
saveSvgAsPng is not working in Safari 10.0.1
I have tested it on: 
Safari version 10.0.1 - not working
Safari version 9.1.2 - works

https://jsfiddle.net/ziinfo/qj56axqk/

**Comment by amergin** [comment]
I'm seeing this problem too. I've been using the same conversion method as `saveSvgAsPng` does in my code, and it has been working in the past in Safari, but not properly in the newest version.

**Comment by exupero** [comment]
Can you be more specific about what's not working? Does the download fail? Are there any errors in the developer console? Does the [test page](http://exupero.org/saveSvgAsPng/) show any images?

**Comment by amergin** [comment]
@exupero: In the jsfiddle above, the download is not triggered. Only one error in console ("Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag.") but it's presumably related to the Jsfiddle sandbox.

Test page:
With linked SVG image -> Preview is empty
At a higher resolution -> In preview pixelated rectangle is missing
With foreign objects -> Preview empty
When setting xmlns on foreign object children -> Preview empty
With custom fonts -> Preview empty

Console:
![image](https://cloud.githubusercontent.com/assets/1969229/21264821/05fd0360-c3a7-11e6-9012-e7a1b9c549dd.png)

**Comment by massone** [comment]
@amergin: I don't think it's Jsfiddle related, you don't get this error in Chrome and it works in Safari 9 despite the error

**Comment by massone** [comment]
@exupero: Safari 10 renders images correctly, however I get error:
`Rendered SVG images cannot be downloaded in this browser.`

**Comment by exupero** [comment]
Sounds like Safari 10 throws a `SecurityError` like IE. You'll likely need to use canvg to work around it. See the [Support section](https://github.com/exupero/saveSvgAsPng#support) of the Readme.

**Comment by ziinfo** [comment]
Just spotted:
With foreign objects -> Preview empty
When setting xmlns on foreign object children -> Preview empty

the rest renders fine

**Comment by Jephuff** [comment]
If you turn off the popup blocker, it should open the png.
unfortunately it doesn't seem that safari supports the download attribute on anchor tags, not sure if there is a fix for that.
