### ISSUE TITLE
mermaid svg to png issue

### ISSUE THREAD

**Issue by shd101wyy** [exupero/saveSvgAsPng#128]
Hi, this is an awesome library.

I was trying to convert mermaid svg to png using this library, but the result png seems to be wrong.  
Any idea why this happened? 

![screen shot 2017-01-11 at 10 43 53 pm](https://cloud.githubusercontent.com/assets/1908863/21877293/9258b176-d84f-11e6-998f-7c3e7a1a163e.png)

It works correctly [here](http://codepen.io/grofit/pen/KzjVvy?editors=1010) though.  
The source code can be downloaded [mermaid-svgsave-issue.zip](https://github.com/exupero/saveSvgAsPng/files/700699/mermaid-svgsave-issue.zip)

Thank you very much ;)

**Comment by exupero** [comment]
My first guess is that the SVG is taking advantage of some built-in browser styles. Those don't get compiled into the SVG that's rendered to canvas. Try manually specifying the styles of the rectangles and lines that don't appear correctly.

**Comment by shd101wyy** [comment]
It seems that it would cause problem if I include css like `<link href="....css">`, but it works if I include css directly within `<style>...</style>`.
