### ISSUE TITLE
In chrome, download doesnt happen for more than 1.5MB png file

### ISSUE THREAD

**Issue by pranavq212** [exupero/saveSvgAsPng#133]
I am using saveSvgAsPng.js to save my svg as png.In chrome(chrome Version 55.0.2883.87 (64-bit)), i am not able to download png file more than 1.5MB . I have close to 500 nodes and the download to png file is close to 1.6MB and its throwing error in chrome. But works fine in Firefox for more than 2.5MB.

I can't use scale option since there is requirement for scale 100 at any size. I am getting error "**`Failed - Network error`**". **There is no error in console for network xhr request.** I am adding screen shot of error.

<a href="http://imgur.com/KwikTd5"><img src="http://i.imgur.com/KwikTd5.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/VWCc4Vk"><img src="http://i.imgur.com/VWCc4Vk.png" title="source: imgur.com" /></a>
Please help.

**Comment by exupero** [comment]
The only time this lib uses the network is to inline images and CSS, so a networking error should show up regardless of the size of the resulting PNG.

Does this apply to rendering the PNG or only to downloading it? You can try rendering it without downloading using the exported function `svgAsPngUri` ([see here](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L348)) and setting the `src` attribute of an image tag to the data URI given to the callback function. If the image shows up in browser, it would seem to be a downloading limitation in Chrome, and I don't know of anything this library can do about that.

**Comment by pranavq212** [comment]
Yes, that is chrome specific issue. Works fine for Firefox for much larger size.  I have found some hack for fixing but that breaks Firefox &  IE. 

Just looking something clean &  not browser dependent not successful so far.

**Comment by pranavq212** [comment]
Chrome has data URI limit of 2MB [http://stackoverflow.com/a/41755526/704008](url). It's just shocking since all other browsers allow much high URI limit. Looking into this solution [http://stackoverflow.com/questions/38781968/problems-downloading-big-filemax-15-mb-on-google-chrome](url) but again as I said this is different code for IE, chrome & firefox and might be again different for some other browser OR combination of browser/platform. 
Quite frustrating to see altogether different implementation of simple URI solution :(

**Comment by exupero** [comment]
Thanks for digging up that info. I've added a note to the Readme to that effect.

**Comment by pranavq212** [comment]
Added pull request for fix. 
[https://github.com/exupero/saveSvgAsPng/pull/134](https://github.com/exupero/saveSvgAsPng/pull/134)

Please check working fine now for all browsers including chrome for large files
