### ISSUE TITLE
Invalid CSS Selector

### ISSUE THREAD

**Issue by coonsa2** [exupero/saveSvgAsPng#135]
I'm getting Invalid CSS "warnings" when trying to save my nvd3 graph such as the following:

Invalid CSS selector "[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)" DOMException: Failed to execute 'querySelector' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)' is not a valid selector.

These are occuring at saveSvgAsPng.js:102. 

`<div id="cost">
                <svg id="costSVG"></svg>
            </div>`

`saveSvgAsPng(document.getElementById("costSVG"), "costGraph.png");`

If you need any specific information from the svg it's sending let me know. I read through past issues where this seemed to be a problem like issue #11 and #71 however this seems to be a new issue. 

Note: I'm using ripple with chrome

**Comment by exupero** [comment]
Invalid selectors should be handled in newer versions. If the problem exists after 1.4.0, please re-open.
