### ISSUE TITLE
[HELP] svgAsPngUri() not working - need help for usage

### ISSUE THREAD

**Issue by r6174** [exupero/saveSvgAsPng#141]
I am unable to store the svg image in the server with the specified uri , please guide me how to use it

Thanks

**Comment by exupero** [comment]
This library isn't designed for server-side creation of PNGs. It relies on in-browser functionality for downloading images.

If you're creating a PNG data URI in-browser and sending it to the server, you'll need to convert the data URI into a binary file. How to do that will depend on the platform/language, and is out of scope for this library.
