### ISSUE TITLE
Multi svg in one png

### ISSUE THREAD

**Issue by shadirok** [exupero/saveSvgAsPng#142]
Hello,
Is there any way to handle many svg and get them into one PNG image.

Thanks.

**Comment by exupero** [comment]
There may be a couple ways to go about this. You might be able to refer to other SVGs on a page using the SVG <image> tag. I'm not sure, though, if this library will capture them properly. Alternatively, you could write several images to a canvas at different positions, then use this library's `download` function to download the data URI of the combined image.
