### ISSUE TITLE
Svg elements with percentage-based widths cause errors when canvg function is specified

### ISSUE THREAD

**Issue by JammG** [exupero/saveSvgAsPng#144]
Hi, I'm using the canvg option for internet explorer support. I've run across an issue with svg elements that have percentage based widths (maybe heights as well). When the svg element is cloned and passed to canvg it produces the following error: 

`Uncaught TypeError: Cannot read property 'width' of undefined`

I believe this has something to do with canvg using parent elements to resolve percentage based dimensions. If it was just an inline style, I could find a fairly simple workaround, but this seems to occur if width / height is specified in a stylesheet as well, and these come from a library that I'd rather not modify.

I have tried:

- Setting an inline style on the svg element.
- Specifying an explicit width and height, on the options object.
- Changing the style, using the modifyStyle function - this does work but I'm not able to tell which element styles are being applied to with this function, so I'm not fond of this solution.

Any suggestions would be appreciated!

Thanks!

**Comment by exupero** [comment]
I'm open to a PR for this. I'm not familiar enough with canvg.

**Comment by exupero** [comment]
I'm closing this as it sounds like a bug with canvg. If I'm wrong, and there's something this library can do to resolve the error, please re-open.
