### ISSUE TITLE
How to properly install it in angular 2 (type script).

### ISSUE THREAD

**Issue by awaisaltaf** [exupero/saveSvgAsPng#145]
Hi,
I successfully installed 
npm install save-svg-as-png --save 
in my angular2 app but its saying saveSvgAsPng is not a function. how to include it in component.
As for as my thinking is i am missing its type. so i try to install these
typings install save-svg-as-png
npm install @type/save-svg-as-png --save 
But both not working can any one help me what i am doing wrong.

**Comment by exupero** [comment]
I'm not familiar enough with either angular 2 or typescript to know the proper way to access the library, but if you include the script tag in the HTML, `saveSvgAsPng` should be available on the `window` object. I believe you can manually add the proper typings to the window object within your code. I don't know of any typings to install for this library.

**Comment by andrea06590** [comment]
**In angular 2+** npm i save-svg-as-png **then add the script to your** .angular-cli.json file
**in your component  :** declare let svgAsPngUri: any;
_in case you just need this function_

**Comment by exupero** [comment]
That's for the tip.

I'm going to close this issue as unrelated to this library.
