### ISSUE TITLE
Getting 'Cannot set property 'prepareSvg' of undefined' when deploy in tomcat 8

### ISSUE THREAD

**Issue by eglez92** [exupero/saveSvgAsPng#148]
Hey hope you can help me with this. I'm using saveSvgAsPng.js to get a PNG file from a SVG generated by NVD3.js when I run the project in local (grunt serve) is ok but when I run it on Tomcat I'm getting 'Cannot set property 'prepareSvg' of undefined'.
Is there any solution?

**Comment by exupero** [comment]
This doesn't sound like a problem with this library, but with your JS being served when your app runs under Tomcat. Check to make sure the file is being loaded by the browser and served by the server. If it is, see if saveSvgAsPng.js is being minified, which may mangle the expected names.
