### ISSUE TITLE
Issues with texts

### ISSUE THREAD

**Issue by augustom87** [exupero/saveSvgAsPng#15]
Issue: In my SVG I have a circle with some text inside ("new"). When I export as PNG the texts are not appearing. I append my SVG with the styles.

<svg width="1280" height="286" id="svg">
  <g class="container_slider">
     <g class="graph">
        <g>
          <g class="conceptG" id="node_2" transform="translate(655,129)">
               <circle r="50"></circle>
               <text text-anchor="middle" dy="-0">
                 new
               </text>
           </g>
        </g>
      </g>
 </g>

<style>
g.conceptG circle, g.selected circle, g.target circle {
fill: #FFFFFF;
stroke: #333;
stroke-width: 1px;}
</style>

</svg>

**Comment by lebolo** [comment]
Can you post some code, specifically what your DOM and SVG element structure looks like and what classes they have.

You might also want to look at #12 and #13.

**Comment by augustom87** [comment]
Thanks a lot!
Im ashamed I didnt see that examples before!
It was that the css rules where not directly applying to my text!
