### ISSUE TITLE
editor/ui-grid.eot 404 (Not Found)

### ISSUE THREAD

**Issue by curiousPup** [exupero/saveSvgAsPng#153]
Getting this error while converting an SVG on line 205 ( oReq.send(); )of saveSvgAsPng.js 

var oReq = new XMLHttpRequest();
        oReq.addEventListener('load', fontLoaded);
        oReq.addEventListener('error', transferFailed);
        oReq.addEventListener('abort', transferFailed);
        oReq.open('GET', font.url);
        oReq.responseType = 'arraybuffer';
        oReq.send();

**Comment by exupero** [comment]
It sounds like your CSS or a CSS library you're using refers to the font file `editor/ui-grid.eot`, but your server is returning a 404 Not Found. I've added error catching around the call to that `.send()` that will log the error. Try [this branch](https://github.com/exupero/saveSvgAsPng/tree/fix/font-load-failure) and let me know if that improves the clarity of the failure. If that change is suitable, I'll merge in #154.

**Comment by curiousPup** [comment]
Doesn't help. I'm still getting the same error

**Comment by curiousPup** [comment]
Okay so I got rid of this error. But now image.onload is not getting fired.
Any leads on that please?

**Comment by exupero** [comment]
Is `image.onerror` being triggered?

Can you supply a minimal reproduction of the problem?

**Comment by darkdoon** [comment]
same problem here. 
```
GET http://localhost:3000/common-images/spreadsheet/ejxlicons.eot? 404 (Not Found) 
GET http://localhost:3000/ui-grid.eot  404 (Not Found)
```

at line 200 (`oRes.send()`)

My navigator fetch .woff font files by default, don't know why, but .eot are not loaded.

**Comment by curiousPup** [comment]
Version of this library publish in bower repo doesn't have this issue. You can try that.
