### ISSUE TITLE
Error by interpreting HTML tags in attribute values of SVG Elements

### ISSUE THREAD

**Issue by tgotwig** [exupero/saveSvgAsPng#161]
Hey there 🤗
I get an error for using HTML tags in attribute values,
for example:
```html
<line title="<div>TEST</div>"></line>
```

**Comment by exupero** [comment]
It appears that attribute values can't contain unescaped `<` or `>`. Nor can they apparently contain `&lt;` or `&gt;`. The closest I could get was to use `&amp;lt;` and `&amp;gt;`.

But you may not actually need this ability. SVG element titles should be included as child tags, as in

```svg
<line><title>TEST</title></line>
```
