### ISSUE TITLE
Not working in IE - error code XML5634

### ISSUE THREAD

**Issue by ghost** [exupero/saveSvgAsPng#167]
Hi,

For me it is not working in IE, I get this error:
XML5634: An attribute with the same name already exists on this element. Line: 1, Column 320

Any suggestions?

Thanks

**Comment by exupero** [comment]
It sounds like your XML may have a duplicate attribute on some tag. I don't think this library would cause such an error, as it overwrites existing attributes, but if you provide example code that demonstrates the problem, I'll take a look.

**Comment by ghost** [comment]
Hi,

Thank you for your reply.
This is my code: 

      `var svg = document.querySelector("svg");
        window.onbeforeunload = null;

        svgAsPngUri(svg, {modifyCSS : {'text' : 'font-family:' + myAPP.selectedFont}}, function(uri) {
           save_img(uri); // This is an ajax function for processing the image
        });`

Attached you will find a screenshot with the error (it only appears in Internet Explorer). I am ussing IE11 and I have already tested it for svg support, it should work without the canvg option. I have already tried with the canvg option and it gives me several errors, rooting in the XML parsing section.

Also attached you will find a file with the HTML of the svg I'm working on (I am generating the svg with svg.js). If you check it with notepad++ you will notice that line 1, column 320 is found on the first "B" of the svg background image base64 encoding (in the xlink:href tag of the image element).
I don't have that much experience working with svg so I really appreciate any suggestion / advice. I'd be happy to provide any other information you might need. Thank you!

[svg_html.txt](https://github.com/exupero/saveSvgAsPng/files/1939062/svg_html.txt)
![ie_error](https://user-images.githubusercontent.com/22426862/39138476-aacc9008-4728-11e8-91a8-6aef31dfd0bf.jpg)

**Comment by exupero** [comment]
Sorry it's taken me so long to look into this. The SVG code you provided has an `<svg>` tag with two `xmlns` attributes, and IE may be more sensitive to that than other browsers.

This sounds like something that svg.js may be doing, but if not, feel free to reopen this issue.

**Comment by ghost** [comment]
Hi Eric,Thank you for taking the time to look into this. I'll try to find a way to eliminate one tag, hopefully it'll "please" IE :)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Eric ShullSent: luni, 14 mai 2018, 23:50To: exupero/saveSvgAsPngReply To: exupero/saveSvgAsPngCc: JediCate; AuthorSubject: Re: [exupero/saveSvgAsPng] Not working in IE - error code XML5634 (#167)Sorry it's taken me so long to look into this. The SVG code you provided has an <svg> tag with two xmlns attributes, and IE may be more sensitive to that than other browsers.
This sounds like something that svg.js may be doing, but if not, feel free to reopen this issue.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/exupero/saveSvgAsPng","title":"exupero/saveSvgAsPng","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/exupero/saveSvgAsPng"}},"updates":{"snippets":[{"icon":"PERSON","message":"@exupero in #167: Sorry it's taken me so long to look into this. The SVG code you provided has an `\u003csvg\u003e` tag with two `xmlns` attributes, and IE may be more sensitive to that than other browsers.\r\n\r\nThis sounds like something that svg.js may be doing, but if not, feel free to reopen this issue."}],"action":{"name":"View Issue","url":"https://github.com/exupero/saveSvgAsPng/issues/167#issuecomment-388958143"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [exupero/saveSvgAsPng] Not working in IE - error code XML5634 (#167)","sections":[{"text":"","activityTitle":"**Eric Shull**","activityImage":"https://avatars2.githubusercontent.com/u/287159?s=160\u0026v=4","activitySubtitle":"@exupero","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"exupero/saveSvgAsPng\",\"issueId\":167,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"targets":[{"os":"default","uri":"https://github.com/exupero/saveSvgAsPng/issues/167#issuecomment-388958143"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":326873679}"}],"themeColor":"26292E"}
