### ISSUE TITLE
Unable to use https://github.com/exupero/saveSvgAsPng/blob/gh-pages/src/saveSvgAsPng.js as source

### ISSUE THREAD

**Issue by harishshankar23** [exupero/saveSvgAsPng#177]
Hi,

I am using saveSvgAsPng to generate a file to read the contents of the svg. In my code i have used "https://rawgit.com/exupero/saveSvgAsPng/gh-pages/saveSvgAsPng.js" as the script source to access "svgAsDataUri". When i run the page where the link mentioned above is used it throws "Refused to execute script from 'https://rawgit.com/exupero/saveSvgAsPng/gh-pages/saveSvgAsPng.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled." I tried with the below URL as well. Still i was getting the same when click the save link on the page.
https://github.com/exupero/saveSvgAsPng/blob/gh-pages/src/saveSvgAsPng.js .

Could you please me with the how should i go with this. Thanks in Advance.

Thanks,
Harish S

**Comment by exupero** [comment]
You can link directly to the source script with this URL: http://exupero.org/saveSvgAsPng/src/saveSvgAsPng.js

That's an ES6 file, so if you need ES5 compatibility, you'll need to get the module from NPM.
