### ISSUE TITLE
Can set the color when exporting PNG?

### ISSUE THREAD

**Issue by ALein** [exupero/saveSvgAsPng#180]
I now make an icon library, hoping to set up the color when SVG is downloaded to PNG, and I don't know how to do it.

**Comment by exupero** [comment]
Use the `modifyCss` option. Here's an example:

https://github.com/exupero/saveSvgAsPng/blob/320b56aca265dc410f58ff60d1099ed2cfc4e926/index.js#L50-L54

Let me know if you need something different.

**Comment by ALein** [comment]
I'm using a remote SVG , which has a originally  color, and now I want to change this color when I download it, so you can download a PNG map of different colors.

**Comment by ALein** [comment]
I'm using a remote SVG , which has a originally color, and now I want to change this color when I download it, so you can download a PNG map of `different` colors.modifyCss can only modify my custom outer style。
` <svg width=128 height=128  id="svg-wrap">
            <image v-bind:xlink:href=downloadIcon.src x=0 y=0 width=128 height=128 id="svg-con"/>
          </svg>`

**Comment by exupero** [comment]
Thank you for the clarification. If you want to modify a remote SVG, you'll have to download it with an XHR request and modify the XML. This library doesn't have facility for that.

**Comment by ALein** [comment]
Thank you!

**Comment by ALein** [comment]
Thank you very much！
