### ISSUE TITLE
Fully qualified URLs in attributes break in exported SVGs

### ISSUE THREAD

**Issue by lijingjian001** [exupero/saveSvgAsPng#190]
my svg html show is 
![image](https://user-images.githubusercontent.com/12969526/45292490-fbf09480-b527-11e8-9e1a-5f9b74cccae6.png)
but i export is 
![image](https://user-images.githubusercontent.com/12969526/45292517-0e6ace00-b528-11e8-9f27-ce7d030e8cc3.png)

And I found in the svg . linearGradient Is Ignored.  Is a Bug?

**Comment by exupero** [comment]
Can you create a JSFiddle that reproduces this issue so I can investigate? Thanks.

**Comment by lijingjian001** [comment]
You Can See on this link. Right click and save as img. You Can see the result of convert svg to img.
https://jsfiddle.net/ShyRedwolf/a63150rd/73/

**Comment by exupero** [comment]
Thanks, that helps a lot. The quick fix is to remove the URL portion from the `fill` attribute on this element:

```xml
<path d="M 225.5 20 L 385.5 20 L 385.5 180 L 225.5 180 Z"
  fill="url(https://fiddle.jshell.net/a63150rd/77/show/#mx-gradient-c3d9ff-1-white-1-s-0)"
  stroke="#6482b9" stroke-miterlimit="10" pointer-events="all"></path>
```

and just use the hash fragment, as in

```xml
<path d="M 225.5 20 L 385.5 20 L 385.5 180 L 225.5 180 Z"
  fill="url(#mx-gradient-c3d9ff-1-white-1-s-0)"
  stroke="#6482b9" stroke-miterlimit="10" pointer-events="all"></path>
```

To have the library handle this situation, it would need to check XML attributes like `fill` for fully qualified paths and manipulate them. I'm open to a pull request for that.

**Comment by lijingjian001** [comment]
Thanks,I have deal the problem of my project.And It looks fine now,Should I close this comment?

**Comment by exupero** [comment]
Great!
