### ISSUE TITLE
resulting PNG includes hidden text labels

### ISSUE THREAD

**Issue by quartzeeee** [exupero/saveSvgAsPng#196]
We have a map of the US but when zoomed in on any place with more than 1 state label, it's including a label on everything.  For instance, on the Michigan upper peninsula it's including many labels on islands instead of one label for the state.

![map](https://user-images.githubusercontent.com/44817247/48166041-0374b580-e2ad-11e8-98ce-ead95d076e20.png)

![map2](https://user-images.githubusercontent.com/44817247/48209305-65c7c780-e33a-11e8-9d6c-23e8051000ed.png)

The markup shows many of these labels as hidden in the css but they're still being saved.

**Comment by exupero** [comment]
How exactly are the labels hidden in the CSS? I'll see if I can reproduce it and then troubleshoot what's going on.

**Comment by quartzeeee** [comment]
I appreciate you getting back to me, this was an issue on our side after all with a mismatched css file.
