### ISSUE TITLE
Background image problem

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [exupero/saveSvgAsPng#198]
when my save background is a image uri, the background was download transparent .
link 

`<svg style="background:url(base64code)"></svg>`

**Comment by exupero** [comment]
How are you calling `saveSvgAsPng`? The default background is transparent, but you can specify another color using the `backgroundColor` option.

**Comment by xiaoshidetaikuai** [comment]
> How are you calling `saveSvgAsPng`? The default background is transparent, but you can specify another color using the `backgroundColor` option.

`backgroundColor` is normal ， but when background is an image,  you can try export have an image background svg. but  I used your previous version can export it successful.

**Comment by exupero** [comment]
Thanks for the bug report. I understand now. I'll take a look at including background images via the `style` attribute.

**Comment by exupero** [comment]
I've pushed version 1.4.8 that fixes a bug where the background color was being overridden. Sorry it took so long.
