### ISSUE TITLE
SVG error

### ISSUE THREAD

**Issue by fongtak** [exupero/saveSvgAsPng#199]
Hi, I try to transfer svg generated by mathjax to png, but I encounter a bug when using Chrome. I can get the png successfully when using Edge. Here is the bug report : 

```
Uncaught (in promise) There was an error loading the data URI as an image on the following SVG
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd .......

```
And here is my svg string : 

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="38" height="44" viewBox="306,285,38,44"><defs><clipPath id="clip-1"><rect x="13726.10366" y="12999.40987" transform="scale(0.02323,0.02322)" width="529.5" height="615.4" fill="none" stroke="none"></rect></clipPath></defs><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g clip-path="url(#clip-1)" data-paper-data="{&quot;content&quot;:&quot;<svg xmlns:xlink=\&quot;http://www.w3.org/1999/xlink\&quot; width=\&quot;1.23ex\&quot; height=\&quot;1.429ex\&quot; viewBox=\&quot;0 -511.5 529.5 615.4\&quot; role=\&quot;img\&quot; focusable=\&quot;false\&quot; style=\&quot;vertical-align: -0.241ex;\&quot;><defs><path stroke-width=\&quot;1\&quot; id=\&quot;E1-MJMATHI-61\&quot; d=\&quot;M33 157Q33 258 109 349T280 441Q331 441 370 392Q386 422 416 422Q429 422 439 414T449 394Q449 381 412 234T374 68Q374 43 381 35T402 26Q411 27 422 35Q443 55 463 131Q469 151 473 152Q475 153 483 153H487Q506 153 506 144Q506 138 501 117T481 63T449 13Q436 0 417 -8Q409 -10 393 -10Q359 -10 336 5T306 36L300 51Q299 52 296 50Q294 48 292 46Q233 -10 172 -10Q117 -10 75 30T33 157ZM351 328Q351 334 346 350T323 385T277 405Q242 405 210 374T160 293Q131 214 119 129Q119 126 119 118T118 106Q118 61 136 44T179 26Q217 26 254 59T298 110Q300 114 325 217T351 328Z\&quot;></path></defs><g stroke=\&quot;currentColor\&quot; fill=\&quot;currentColor\&quot; stroke-width=\&quot;0\&quot; transform=\&quot;matrix(1 0 0 -1 0 0)\&quot;><use xlink:href=\&quot;#E1-MJMATHI-61\&quot; x=\&quot;0\&quot; y=\&quot;0\&quot;></use></g></svg>&quot;,&quot;type&quot;:&quot;latex&quot;,&quot;uid&quot;:1}"><g fill="#000000" stroke="#000000"><path d="M319.61657,310.08673c0,-1.56353 0.58848,-3.04965 1.76544,-4.45837c1.17696,-1.40872 2.50104,-2.12082 3.97224,-2.1363c0.7898,0 1.48669,0.37927 2.09065,1.13781c0.24778,-0.46441 0.60397,-0.69662 1.06856,-0.69662c0.20132,0 0.37941,0.06192 0.53428,0.18577c0.15486,0.12384 0.23229,0.27865 0.23229,0.46441c0,0.20125 -0.2865,1.43968 -0.85949,3.71531c-0.57299,2.27563 -0.86723,3.5605 -0.88272,3.85463c0,0.38701 0.0542,0.64244 0.16261,0.76628c0.1084,0.12384 0.27101,0.19351 0.48782,0.20899c0.13938,-0.01548 0.29424,-0.08514 0.46459,-0.20899c0.32521,-0.30961 0.64268,-1.05267 0.95241,-2.22918c0.09292,-0.30961 0.17035,-0.47215 0.23229,-0.48763c0.03097,-0.01548 0.1084,-0.02322 0.23229,-0.02322h0.09292c0.29424,0 0.44136,0.06966 0.44136,0.20899c0,0.09288 -0.03872,0.30187 -0.11615,0.62696c-0.07743,0.32509 -0.23229,0.74306 -0.46459,1.25392c-0.23229,0.51085 -0.48008,0.89787 -0.74334,1.16103c-0.20132,0.20125 -0.4491,0.36379 -0.74334,0.48763c-0.12389,0.03096 -0.30973,0.04644 -0.55751,0.04644c-0.52653,0 -0.96789,-0.1161 -1.32408,-0.34831c-0.35619,-0.23221 -0.58848,-0.47215 -0.69688,-0.71984l-0.13938,-0.34831c-0.01549,-0.01548 -0.04646,-0.00774 -0.09292,0.02322c-0.03097,0.03096 -0.06195,0.06192 -0.09292,0.09288c-0.91369,0.8669 -1.84287,1.30036 -2.78754,1.30036c-0.85175,0 -1.60283,-0.30961 -2.25326,-0.92883c-0.65042,-0.61922 -0.97564,-1.60223 -0.97564,-2.94903zM327.00354,306.11599c0,-0.09288 -0.03872,-0.26317 -0.11615,-0.51085c-0.07743,-0.24769 -0.25552,-0.51859 -0.53428,-0.81272c-0.27875,-0.29413 -0.63494,-0.44893 -1.06856,-0.46441c-0.54202,0 -1.06081,0.23995 -1.55637,0.71984c-0.49556,0.47989 -0.88272,1.10685 -1.16147,1.88087c-0.4491,1.22296 -0.76657,2.49235 -0.95241,3.80819c0,0.04644 0,0.13158 0,0.25543c0,0.12384 -0.00774,0.21673 -0.02323,0.27865c0,0.69662 0.13938,1.17651 0.41813,1.43968c0.27875,0.26317 0.61171,0.40249 0.99887,0.41797c0.58848,0 1.16922,-0.25543 1.74221,-0.76628c0.57299,-0.51085 0.91369,-0.90561 1.0221,-1.18425c0.03097,-0.06192 0.24004,-0.89013 0.6272,-2.48461c0.38716,-1.59449 0.58848,-2.45365 0.60397,-2.57749z" id="E1-MJMATHI-61 1"></path></g></g></g></svg>`

Can you help me ?
Thanks a lot!

**Comment by exupero** [comment]
I've found that Firefox will give the exact location of SVG errors, and it appears that the problem is `<` characters within the attribute `data-paper-data`. Replacing `<` with `&gt;` in that value renders the SVG (a letter `a`).

**Comment by amrit-kumar** [comment]
I am getting the same error:`ERROR Error: Uncaught (in promise): There was an error loading the data URI as an image on the following SVG`

the complete stacktrace is as below:
`ERROR Error: Uncaught (in promise): There was an error loading the data URI as an image on the following SVG
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [<!ENTITY nbsp "&#160;">]><svg class="ngx-charts" width="2400" height="1140" version="1.1" viewBox="-44.375 -12.203125 800 380" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background-color: transparent;"><defs><style type="text/css"><![CDATA[
.dismissButton { background-color: rgb(255, 255, 255); border: 1px solid rgb(218, 220, 224); color: rgb(26, 115, 232); border-radius: 4px; font-family: Roboto, sans-serif; font-size: 14px; height: 36px; cursor: pointer; padding: 0px 24px; }
.dismissButton:hover { background-color: rgba(66, 133, 244, 0.04); border: 1px solid rgb(210, 227, 252); }
.dismissButton:focus { background-color: rgba(66, 133, 244, 0.12); border: 1px solid rgb(210, 227, 252); outline: 0px; }
.dismissButton:hover:focus { background-color: rgba(66, 133, 244, 0.16); border: 1px solid rgb(210, 226, 253); }
.dismissButton:active { background-color: rgba(66, 133, 244, 0.16); border: 1px solid rgb(210, 226, 253); box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px; }
.dismissButton:disabled { background-color: rgb(255, 255, 255); border: 1px solid rgb(241, 243, 244); color: rgb(60, 64, 67); }
.gm-control-active > img { box-sizing: content-box; display: none; left: 50%; pointer-events: none; position: absolute; top: 50%; transform: translate(-50%, -50%); }
.gm-control-active > img:nth-child(1) { display: block; }
.gm-control-active:hover > img:nth-child(1), .gm-control-active:active > img:nth-child(1) { display: none; }
.gm-control-active:hover > img:nth-child(2), .gm-control-active:active > img:nth-child(3) { display: block; }
.gm-ui-hover-effect { opacity: 0.6; }
.gm-ui-hover-effect:hover { opacity: 1; }
.gm-style .gm-style-cc span, .gm-style .gm-style-cc a, .gm-style .gm-style-mtc div { font-size: 10px; box-sizing: border-box; }
.gm-style-pbc { transition: opacity 0s ease-in-out 0s; background-color: rgba(0, 0, 0, 0.45); text-align: center; }
.gm-style-pbt { font-size: 22px; color: white; font-family: Roboto, Arial, sans-serif; position: relative; margin: 0px; top: 50%; transform: translateY(-50%); }
.fa { display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: 1; font-family: FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased; }
.fa-lg { font-size: 1.33333em; line-height: 0.75em; vertical-align: -15%; }
.fa-2x { font-size: 2em; }
.fa-3x { font-size: 3em; }
.fa-4x { font-size: 4em; }
.fa-5x { font-size: 5em; }
.fa-fw { width: 1.28571em; text-align: center; }
.fa-ul { padding-left: 0px; margin-left: 2.14286em; list-style-type: none; }
.fa-ul > li { position: relative; }
.fa-li { position: absolute; left: -2.14286em; width: 2.14286em; top: 0.142857em; text-align: center; }
.fa-li.fa-lg { left: -1.85714em; }
.fa-border { padding: 0.2em 0.25em 0.15em; border: 0.08em solid rgb(238, 238, 238); border-radius: 0.1em; }
.fa-pull-left { float: left; }
.fa-pull-right { float: right; }
.fa.fa-pull-left { margin-right: 0.3em; }
.fa.fa-pull-right { margin-left: 0.3em; }
.pull-right { float: right; }
.pull-left { float: left; }
.fa.pull-left { margin-right: 0.3em; }
.fa.pull-right { margin-left: 0.3em; }
.fa-spin { animation: 2s linear 0s infinite normal none running fa-spin; }
.fa-pulse { animation: 1s steps(8, end) 0s infinite normal none running fa-spin; }
.fa-rotate-90 { transform: rotate(90deg); }
.fa-rotate-180 { transform: rotate(180deg); }
.fa-rotate-270 { transform: rotate(270deg); }
.fa-flip-horizontal { transform: scale(-1, 1); }
.fa-flip-vertical { transform: scale(1, -1); }
:root .fa-rotate-90, :root .fa-rotate-180, :root .fa-rotate-270, :root .fa-flip-horizontal, :root .fa-flip-vertical { filter: none; }
.fa-stack { position: relative; display: inline-block; width: 2em; height: 2em; line-height: 2em; vertical-align: middle; }
.fa-stack-1x, .fa-stack-2x { position: absolute; left: 0px; width: 100%; text-align: center; }
.fa-stack-1x { line-height: inherit; }
.fa-stack-2x { font-size: 2em; }
.fa-inverse { color: rgb(255, 255, 255); }
.fa-glass::before { content: "ï"; }
.fa-music::before { content: "ï"; }
.fa-search::before { content: "ï"; }
.fa-envelope-o::before { content: "ï"; }
.fa-heart::before { content: "ï"; }
.fa-star::before { content: "ï"; }
.fa-star-o::before { content: "ï"; }
.fa-user::before { content: "ï"; }
.fa-film::before { content: "ï"; }
.fa-th-large::before { content: "ï"; }
.fa-th::before { content: "ï"; }
.fa-th-list::before { content: "ï"; }
.fa-check::before { content: "ï"; }
.fa-remove::before, .fa-close::before, .fa-times::before { content: "ï"; }
.fa-search-plus::before { content: "ï"; }
.fa-search-minus::before { content: "ï"; }
.fazone.js:814)
    at zone.js:724
    at zone.js:740
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3820)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3811)`


and my svg string is following:
`<svg class="ngx-charts" width="405" height="233"><g class="pie-chart chart" transform="translate(202.5, 116.5)"><g ngx-charts-pie-series="" ng-reflect-colors="[object Object]" ng-reflect-series="[object Object],[object Object" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-explode-slices="false" ng-reflect-show-labels="true" ng-reflect-gradient="false" ng-reflect-active-entries="" ng-reflect-trim-labels="true" ng-reflect-max-label-length="10" ng-reflect-tooltip-disabled="false" ng-reflect-animations="false"><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Unknown (RMS 0)" ng-reflect-color="#5bc0de" ng-reflect-max="503066774.801616" ng-reflect-value="503066774.801616" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Unknown (RMS 0)</title><g style="transform: translate3d(86.5px, -14.2239px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: start; shape-rendering: crispedges;"> Unkno... </text></g><path class="pie-label-line line" fill="none" d="M56.88167497419664,-9.482589128202049L85.32251246129496,-14.223883692303072L86.5,-14.223883692303072" stroke="#5bc0de"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#5bc0de" ng-reflect-start-angle="0" ng-reflect-end-angle="2.8112162743813918" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="503066774.801616" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M3.531064937541535e-15,-57.666666666666664A57.666666666666664,57.666666666666664,0,0,1,18.707013388586347,54.54807140975467L0,0Z" fill="#5bc0de" style="pointer-events: auto;"></path></g></g></g><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Light Wood Stud Walls (RMS 1A1" ng-reflect-color="#5cb85c" ng-reflect-max="503066774.801616" ng-reflect-value="321358574.591884" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Light Wood Stud Walls (RMS 1A1)</title><g style="transform: translate3d(-86.5px, 72.9398px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: end; shape-rendering: crispedges;"> Light... </text></g><path class="pie-label-line line" fill="none" d="M-30.99851403201157,48.62650071978885L-46.497771048017356,72.93975107968328L-86.5,72.93975107968328" stroke="#5cb85c"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#5cb85c" ng-reflect-start-angle="2.8112162743813918" ng-reflect-end-angle="4.607018541706577" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="321358574.591884" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M18.707013388586347,54.54807140975467A57.666666666666664,57.666666666666664,0,0,1,-57.34682829674664,6.065123968057302L0,0Z" fill="#5cb85c" style="pointer-events: auto;"></path></g></g></g><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Unknown (RMS IND 0)" ng-reflect-color="#6a533b" ng-reflect-max="503066774.801616" ng-reflect-value="299949817.600467" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Unknown (RMS IND 0)</title><g style="transform: translate3d(-86.5px, -57.8589px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: end; shape-rendering: crispedges;"> Unkno... </text></g><path class="pie-label-line line" fill="none" d="M-42.86723647847163,-38.57258717202198L-64.30085471770745,-57.858880758032974L-86.5,-57.858880758032974" stroke="#6a533b"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#6a533b" ng-reflect-start-angle="4.607018541706577" ng-reflect-end-angle="6.283185307179585" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="299949817.600467" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M-57.34682829674664,6.065123968057302A57.666666666666664,57.666666666666664,0,0,1,-6.181148368199848e-14,-57.666666666666664L0,0Z" fill="#6a533b" style="pointer-events: auto;"></path></g></g></g></g></g></svg>`
Actually i am using **svgAsPngUri** function to create uri of [pie-chart](https://swimlane.github.io/ngx-charts/#/ngx-charts/pie-chart) of [ngx-charts library ](https://github.com/swimlane/ngx-charts) 
any ideas what is going wrong here?

**Comment by amrit-kumar** [comment]
Getting the same error : `ERROR Error: Uncaught (in promise): There was an error loading the data URI as an image on the following SVG`  

**My svg is as below :** 
`<svg class="ngx-charts" width="405" height="233"><g class="pie-chart chart" transform="translate(202.5, 116.5)"><g ngx-charts-pie-series="" ng-reflect-colors="[object Object]" ng-reflect-series="[object Object],[object Object" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-explode-slices="false" ng-reflect-show-labels="true" ng-reflect-gradient="false" ng-reflect-active-entries="" ng-reflect-trim-labels="true" ng-reflect-max-label-length="10" ng-reflect-tooltip-disabled="false" ng-reflect-animations="false"><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Unknown (RMS 0)" ng-reflect-color="#5bc0de" ng-reflect-max="503066774.801616" ng-reflect-value="503066774.801616" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Unknown (RMS 0)</title><g style="transform: translate3d(86.5px, -14.2239px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: start; shape-rendering: crispedges;"> Unkno... </text></g><path class="pie-label-line line" fill="none" d="M56.88167497419664,-9.482589128202049L85.32251246129496,-14.223883692303072L86.5,-14.223883692303072" stroke="#5bc0de"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#5bc0de" ng-reflect-start-angle="0" ng-reflect-end-angle="2.8112162743813918" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="503066774.801616" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M3.531064937541535e-15,-57.666666666666664A57.666666666666664,57.666666666666664,0,0,1,18.707013388586347,54.54807140975467L0,0Z" fill="#5bc0de" style="pointer-events: auto;"></path></g></g></g><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Light Wood Stud Walls (RMS 1A1" ng-reflect-color="#5cb85c" ng-reflect-max="503066774.801616" ng-reflect-value="321358574.591884" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Light Wood Stud Walls (RMS 1A1)</title><g style="transform: translate3d(-86.5px, 72.9398px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: end; shape-rendering: crispedges;"> Light... </text></g><path class="pie-label-line line" fill="none" d="M-30.99851403201157,48.62650071978885L-46.497771048017356,72.93975107968328L-86.5,72.93975107968328" stroke="#5cb85c"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#5cb85c" ng-reflect-start-angle="2.8112162743813918" ng-reflect-end-angle="4.607018541706577" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="321358574.591884" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M18.707013388586347,54.54807140975467A57.666666666666664,57.666666666666664,0,0,1,-57.34682829674664,6.065123968057302L0,0Z" fill="#5cb85c" style="pointer-events: auto;"></path></g></g></g><g class="ng-star-inserted" style=""><g ngx-charts-pie-label="" ng-reflect-data="[object Object]" ng-reflect-radius="57.666666666666664" ng-reflect-label="Unknown (RMS IND 0)" ng-reflect-color="#6a533b" ng-reflect-max="503066774.801616" ng-reflect-value="299949817.600467" ng-reflect-explode-slices="false" ng-reflect-animations="false" ng-reflect-label-trim="true" ng-reflect-label-trim-size="10" class="ng-star-inserted"><title>Unknown (RMS IND 0)</title><g style="transform: translate3d(-86.5px, -57.8589px, 0px);"><text class="pie-label" dy=".35em" style="text-anchor: end; shape-rendering: crispedges;"> Unkno... </text></g><path class="pie-label-line line" fill="none" d="M-42.86723647847163,-38.57258717202198L-64.30085471770745,-57.858880758032974L-86.5,-57.858880758032974" stroke="#6a533b"></path></g><g ngx-charts-pie-arc="" ngx-tooltip="" ng-reflect-tooltip-title="
      <span class=&quot;tooltip-la" ng-reflect-tooltip-disabled="false" ng-reflect-tooltip-placement="top" ng-reflect-tooltip-type="tooltip" ng-reflect-tooltip-context="[object Object]" ng-reflect-fill="#6a533b" ng-reflect-start-angle="4.607018541706577" ng-reflect-end-angle="6.283185307179585" ng-reflect-inner-radius="0" ng-reflect-outer-radius="57.666666666666664" ng-reflect-value="299949817.600467" ng-reflect-max="503066774.801616" ng-reflect-data="[object Object]" ng-reflect-explode-slices="false" ng-reflect-gradient="false" ng-reflect-animate="false" ng-reflect-is-active="false"><g class="arc-group"><path class="arc" d="M-57.34682829674664,6.065123968057302A57.666666666666664,57.666666666666664,0,0,1,-6.181148368199848e-14,-57.666666666666664L0,0Z" fill="#6a533b" style="pointer-events: auto;"></path></g></g></g></g></g></svg>`

Actually i am using **svgAsPngUri** function to create uri of [pie-chart](https://swimlane.github.io/ngx-charts/#/ngx-charts/pie-chart) of [ngx-charts library ](https://github.com/swimlane/ngx-charts) 
Any ideas what is going wrong here?
I have added a text file containing complete stacktrace of error 
[error for generating uri.txt](https://github.com/exupero/saveSvgAsPng/files/3141775/error.for.generating.uri.txt)

Thanks !

**Comment by lifeinchords** [comment]
@amrit-kumar Had the same issues with NGX. That library seems to insert broken SVG syntax

 @exupero's tip led me to narrow this down to tooltips. This fix worked for me: remove tooltip related attributes before passing it to the saveSvgAsPng function

```
const svgEl = document.getElementById(elId).getElementsByTagName('svg')[0]
var elArray = svgEl.querySelectorAll('[ngx-tooltip]')
elArray.forEach(function(element) {
    element.removeAttribute("ng-reflect-tooltip-title")
})
```
