### ISSUE TITLE
This browser does not support object URLs. Falling back to string URL.

### ISSUE THREAD

**Issue by SIRAAJ-UI** [exupero/saveSvgAsPng#209]
When i try to load at chrome i am getting this warning message :This browser does not support object URLs. Falling back to string URL.

Testing from local host its working fine but not working from server.

**Comment by exupero** [comment]
Modify the code below to log the actual error that's being thrown from the `try` block.

https://github.com/exupero/saveSvgAsPng/blob/ccfd5bbf5f5dff9548047aa6d7c7651d0960d897/src/saveSvgAsPng.js#L356-L364

That will give some pointers about what's really going on.

**Comment by ToccataN** [comment]
Was able to resolve this issue by eliminating the requireDomNodePromise function that was recently added. (Feb 10th commit, modified the code locally to previous version).

**Comment by exupero** [comment]
Thanks. I've just published version 1.4.10 with a fix.
