### ISSUE TITLE
Chart style doesn't apply

### ISSUE THREAD

**Issue by oncleguigs** [exupero/saveSvgAsPng#214]
Hi, first of all thank you for this library, it's a great work!

I built a dashboard in nodeJS and EJS displaying some graphs using the NvD3 library. 
I don't know why but when I download the chart points are converted into big black dots.

I'm quite new to JS so there might be something wrong with my code...

_The output on the dashboard:_

![image](https://user-images.githubusercontent.com/42938837/55520484-68042880-5631-11e9-9fb5-80a380dddb03.png)

_The downloaded file.png:_

![plot (11)](https://user-images.githubusercontent.com/42938837/55520474-5d499380-5631-11e9-8ae4-29b2337924d3.png)

_The code for the graph:_

```nv.addGraph(function() {
    var chart = nv.models.scatterChart()
                  .showDistX(true)    //showDist, when true, will display those little distribution lines on the axis.
                  .showDistY(true)
                  .color(d3.scale.category10().range());

    //Configure how the tooltip looks.
    chart.tooltipContent(function(key) {
        return '<h3>' + key + '</h3>';
    });

    //Axis settings
    chart.xAxis.tickFormat(d3.format('.02f'));
    chart.yAxis.tickFormat(d3.format('.02f'));
    chart.xAxis.axisLabel(x_axis.replace(/_/g, ' '));
    chart.yAxis.axisLabel(y_axis.replace(/_/g, ' '));

    d3.select('#chart_' + chart_id + ' svg')
        .datum(data)
        .call(chart)
        .style({ 'width': 600, 'height': 600 })
        .append("text")
        .attr("x", 300)
        .attr("y", -6)
        .attr("text-anchor", "middle")
        .text(title);
    nv.utils.windowResize(chart.update);
    return chart;
  });

d = document.getElementById(svg_idd)
    saveSvgAsPng(d, "plot.png", {'backgroundColor':'white'});

**Comment by exupero** [comment]
I'm not familiar with NvD3, but I'm guessing that the chart's CSS styles have a selector that doesn't match against the SVG. See the readme for hooks to transform CSS selectors, and if you think this is truly a bug with this library, feel free to re-open this issue and supply a JSFiddle or equivalent that demonstrates the problem.

**Comment by oncleguigs** [comment]
I found that this was because of chrome security error throwing : 

> DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet'

Check [this](https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64/49160760#49160760) issue

**Comment by exupero** [comment]
Thanks for the update. Is there anything this library can do about that limitation? Even better error detection would be helpful.
