### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by falali009** [exupero/saveSvgAsPng#215]
saveSvgAsPng.js:232 Uncaught (in promise) TypeError: Cannot destructure property `width` of 'undefined' or 'null'.

from  

https://github.com/chanind/hanzi-writer    

i want download this demo`s   target svg   

	saveSvgAsPng(document.getElementById("target"), "diagram.png");

**Comment by exupero** [comment]
What does `document.getElementById("target")` return? It sounds like its tagName is not "svg" and it has no "getBBox" method.

**Comment by falali009** [comment]
this  target is must be    svg ‘s  id ？

**Comment by exupero** [comment]
It must be the ID of either the SVG node or one of its children. If you're trying to export HTML, take a look at canvg and see if it will do what you want.

**Comment by falali009** [comment]
thank you ！  ORZ~~
