### ISSUE TITLE
<image> with no href, repeated xlink:href, angular attributes

### ISSUE THREAD

**Issue by chrishutchinson** [exupero/saveSvgAsPng#22]
Apologies for the long title, I have a few small issues with this library. I've managed to integrate it about 80% with my project, but am struggling to get the final pieces sorted.

I'm building a tool to wrap up snap.svg into a nice editor, and need to export the built SVG as PNG.

The first issue re. Angular is the same as issue #11 - which I am still having trouble with.

In regards to the other issues, in the case of my project, it is possible an <image> tag could have no `href` attribute, which is causing an issue when saveSvgAsPng is looking for images within the SVG element. Additionally, my project allows images to be streamed in as dataURIs, and I am getting an issue where the `xlink:href` attribute is repeated. I've done my own debugging with the script to get to the xlink error, a screenshot of trying to load the outputted data URI directly is below.

![screen shot 2015-01-12 at 16 36 14](https://cloud.githubusercontent.com/assets/1573022/5706481/3702d402-9a79-11e4-9ed9-62d01afbe73b.png)

I'm wondering if it's due to the way snap.svg adds images to the SVG element, and if line 34 of saveSvgAsPng is contributing to the issue.

You can view my project in it's current form here - http://times.github.io/cardkit-v2/#/ - codebase is here - https://github.com/times/cardkit-v2.

**Comment by SamWhitby** [comment]
I ran into the same issue where the xlink:href attribute was being repeated.
I changed line 18 to this 
var href = image.getAttributeNS("http://www.w3.org/1999/xlink", 'href');
and line 34 to this
image.setAttributeNS("http://www.w3.org/1999/xlink", 'xlink:href', canvas.toDataURL('image/png'));
so the href attribute was set with the correct namespace.

**Comment by danswick** [comment]
I had the same issue. Changed both instances of `xlink:href` (lines 18 and 34) to just `href` and everything worked as expected.

@SamWhitby, I tested your solution and it worked as well and seems to be a better and more explicit solution. Thanks.

**Comment by bastrapp** [comment]
I had the same issue, both your solutions worked fine. 

Thank you!

**Comment by exupero** [comment]
Should be fixed by #33. Let me know if you have any more trouble.
