### ISSUE TITLE
Custom tags were not displayed in the result .png

### ISSUE THREAD

**Issue by liuqiyuan** [exupero/saveSvgAsPng#225]
First of all, this is a great library which is very easy to use!

I found the ```<line>``` tags inside my svg were not displayed in the final exported png file, the nodes ```<circle>``` were displayed correctly though. What were the potential reasons? Also, the fonts seem messed up as well.

The ```<line>``` tag examples which were not displayed are as below:
![Screen Shot 2019-07-23 at 10 02 59 PM](https://user-images.githubusercontent.com/3155179/61766608-440e5380-ad96-11e9-8d1f-32f8cf67a642.png)

And the final .png did not contain these tags:
![network d3](https://user-images.githubusercontent.com/3155179/61766653-79b33c80-ad96-11e9-8f67-3b19ad56987f.png)

**Comment by exupero** [comment]
Looks like some styles aren't being inlined. Try adding a stroke attribute to the lines, and specifying the font characteristics on the `text` objects.

**Comment by liuqiyuan** [comment]
put styles inline worked. Thanks.
