### ISSUE TITLE
when <svg> has <img>,con't show the imge in the png

### ISSUE THREAD

**Issue by zhiySun** [exupero/saveSvgAsPng#229]
i have a problem with downloading svg as png,when <svg> has chlidren <image>,images in svg not rendering in final png.

**Comment by sbatson5** [comment]
@zhiySun How did you resolve this? I am running into the same issue

**Comment by sbatson5** [comment]
In case anyone else runs into this issue, when I was creating the SVG, we were using `href` for the image urls, but updating to `xlink:href` fixed it

**Comment by zhiySun** [comment]
实在抱歉，我并没有完全的解决这个问题。
我是发现已经有人提交过类似的问题，所以我把我的问题关闭了。
之后我通过搜索资源，知道了一些解决办法：
他们提示说可以先将<img&gt;取出来，然后在将<img&gt;按照<svg&gt;中的位置放置到绘画板中。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Scott Batson"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 凌晨5:51
收件人:&nbsp;"exupero/saveSvgAsPng"<saveSvgAsPng@noreply.github.com&gt;;
抄送:&nbsp;"孙志烨"<654201712@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [exupero/saveSvgAsPng] when <svg&gt; has <img&gt;,con't show the imge in the png (#229)




@zhiySun How did you resolve this? I am running into the same issue
