### ISSUE TITLE
saveSvgAsPng without css styleSheets, modifyCss dosen`t work, who can tell me how to use modifyCss

### ISSUE THREAD

**Issue by zhfneu** [exupero/saveSvgAsPng#233]

**Comment by zhfneu** [comment]
I  want to export d3 graph with saveSvgasPng，but without css style

**Comment by peteruithoven** [comment]
@zhfneu any change you can improve the spelling of your title? Maybe shorten it a bit and put some of it in the message?

**Comment by peteruithoven** [comment]
Looks like functions like `modifyCss`, `selectorRemap`, `modifyStyle` are only called for css rules for which the elements can be found in the svg. 
https://github.com/exupero/saveSvgAsPng/blob/be2bb9c63e5abfc219d02389dcaa5fc2e2b763c9/src/saveSvgAsPng.js#L207
