### ISSUE TITLE
i get this  error ReferenceError: excludeUnusedCss is not defined

### ISSUE THREAD

**Issue by bugloos** [exupero/saveSvgAsPng#239]
when is use this library in angular ,get this bug " error ReferenceError: excludeUnusedCss is not defined",after that i find this line https://github.com/exupero/saveSvgAsPng/blob/f88d054efa910aedc02885d6f1ddc7bb4f45b7ac/src/saveSvgAsPng.js#L211
that this variable `excludeUnusedCss` is not define before

**Comment by exupero** [comment]
Thanks. Fixed in 1.4.17.
