### ISSUE TITLE
LeafletJS maps work only partially

### ISSUE THREAD

**Issue by john-clarke** [exupero/saveSvgAsPng#25]
This is a great initiative. I tried to use it on a Leaflet map. However, it seems that there are several SVG layer elements. So I only get certain parts of a map. It would be great to have a more general saveDivAsPng that could include SVG (or not).

Correction: There is only a single SVG layer in my LeafletJS map, but the labels are DIVs and as such do not show up in the png image. Again the solution would be to draw DIV layers including SVG. But I'm not sure this is possible.

**Comment by exupero** [comment]
Take a look at [html2canvas](http://html2canvas.hertzen.com/) and let me know if that does what you want.

**Comment by john-clarke** [comment]
That didn't work so well -- elements missing etc. I think I might use phantomjs -- it gave very good results, but did require that the images be generated serverside.

**Comment by exupero** [comment]
This feature request is out of scope for this library.
