### ISSUE TITLE
call error

### ISSUE THREAD

**Issue by larryhengl** [exupero/saveSvgAsPng#31]
Hi, just tried your lib and immediately hit an error:
Uncaught TypeError: _saveSvgAsPng2.default is not a function

not sure where that is constructed and called.  Tried it two ways: via npm, and simply including the js file into my project.  Same error both ways.  Confirmed I am properly passing in an SVG node and file name.

Any ideas?

thx for sharing the lib.

:Larry

**Comment by exupero** [comment]
It sounds like it's not properly configured for requiring as the default export. You should be able to require it as a module though:

``` javascript
var saveSvgAsPng = require('saveSvgAsPng');
saveSvgAsPng.saveSvgAsPng(...);
```

**Comment by larryhengl** [comment]
speedy response = awesome x appreciated!    thx!

your suggestion made me realize i goofed my es6-style import.  es6.doh()

so i've got it working, however the d3 axes are missing the labels and the styling is off (thick axes).  
ideas?
thanks again,
:L

original svg:
![correct-svg-plot](https://cloud.githubusercontent.com/assets/2637196/7905386/99a58a6c-07cc-11e5-8fba-3a926863c6a0.png)

generated png:
![incorrect-png-plot](https://cloud.githubusercontent.com/assets/2637196/7905396/b4acb394-07cc-11e5-91d0-353d8f7c3c12.png)

**Comment by lebolo** [comment]
There might be some solutions to your last comment in https://github.com/exupero/saveSvgAsPng/issues/12#issuecomment-53117010 and #13. Those issues are a bit old now and I believe some new features have been added to handle this (i.e. the third parameter of `saveSvgAsPng`).

**Comment by larryhengl** [comment]
thanks @lebolo, that helped a lot.  i can now produce a png that is likely close enough to what I need.

i have another Q, but will close this and open another issue regarding that.

thanks again for the pointers!

cheers,
:L
