### ISSUE TITLE
Latest commit just created blank PNGs

### ISSUE THREAD

**Issue by bastrapp** [exupero/saveSvgAsPng#32]
After pulling commit 7872e6388aa7862e8a67b29dc5bd2af75366d341 it only downloads empty images with 300x150 resolution.

**Comment by exupero** [comment]
What browser are you using?

(The [test page](http://exupero.org/saveSvgAsPng/) appears to be working in Firefox and Opera, but Safari seems to have problems.)

**Comment by bastrapp** [comment]
I found the (my) mistake. I am cloning the visible svg element to make some modifications. But the clone does not have values in getBoundingClientRect() as it is not actually drawn. So the changes in commit 7872e6388aa7862e8a67b29dc5bd2af75366d341 do result in width and height of zero.

**Comment by exupero** [comment]
I've added the original code as fallbacks for when there is no client bounding rect. Let me know if you still have trouble with it.

**Comment by bastrapp** [comment]
Works perfectly. Thanks!
