### ISSUE TITLE
saveSvgAsPng() produces dataURI in address field and saves file without extension in Safari

### ISSUE THREAD

**Issue by sheriferson** [exupero/saveSvgAsPng#37]
Hi there,

I am trying to save an SVG with id "timeseriesSVG" to a png.

I use this function call:
`saveSvgAsPng(document.getElementById("timeseriesSVG"), "timeseries.png");`

The image shows up just fine in the Safari tab. However, the address bar doesn't show a path to the png, it's a large chunk of what I'm assuming is dataURI. Example in [this gist](https://gist.github.com/sheriferson/f9add26b9197438eeb93).

If I right-click on the image and click Save Image to "Downloads", the image is saved with filename "Unknown" and no extension, no matter what I suggest as a filename in the function call.

If I drag the image to the desktop, then it does get a png extension, but the filename is still "Unknown.png".

Any ideas on what could be going wrong? Or is this expected behaviour and I'm misinterpreting something?

This happens on Safari 8.0.7, on OS X 10.10.4.

**Comment by exupero** [comment]
Thanks for logging this. Is it possible that `a.download` on [line 159](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L159) doesn't work in Safari?

**Comment by sheriferson** [comment]
Thanks for the response. You might be right. I tried loading the webpage in Chrome and calling the function does download a `.png` file with the provided filename. Safari does not log any errors though. I guess it just doesn't work and fails silently.

Running in Chrome required running a server locally because I was loading a data file from somewhere else on disk, whereas Safari never complained about that, which was a reason for making this application run in Safari in the first place.

Do you foresee a workaround to make that work in Safari too?

**Comment by exupero** [comment]
I don't know of any way to download files differently. I'm open to suggestions.

**Comment by ohenrik** [comment]
The same seems to happen on windows 10 in chrome.

**Comment by ctants** [comment]
Is it possible to open the png at least in an new tab?
I've added
`a.target = "_blank";`
to line 259 but it has no effect.

**Comment by exupero** [comment]
I don't know any way other than that.

**Comment by guilhermesimoes** [comment]
@ctants you can open the png in a new tab using `window.open`. I'll submit a pull request.
