### ISSUE TITLE
Saving charts with Nvd3-Angular

### ISSUE THREAD

**Issue by staklau** [exupero/saveSvgAsPng#40]
I'm trying to use this library with the Nvd3-Angular directive, but I just get an error saying "el.getBBox is not a function". I guess it's because the SVG can't "be found". How can I fix this?

**Comment by exupero** [comment]
How are you passing the SVG element to the function? The docs use `document.getElementById("such-and-such")`. If you're using that, does it return anything?

**Comment by staklau** [comment]
I opened a Stackoverflow question where you can see my code:
http://stackoverflow.com/questions/32137662/savesvgaspng-getbbox-is-not-a-function

**Comment by exupero** [comment]
Thanks for the source code. What does the actual DOM look like when the `saveAsPng` function is called? I don't know what Angular does with the `<nvd3>` tag. Does it transform it into an `<svg>` tag? If so, does that `<svg>` tag have the ID `chart1-svg`?

**Comment by staklau** [comment]
The problem has been resolved at the Stackoverflow question, but there's another problem which may be more familiar to you: The svg file only saves with a gray background. Even if I set "svg {background-color: white;}" in my css file it doesn't render a white background, do you know how to fix this?

**Comment by exupero** [comment]
To my knowledge SVGs can't have a background color. The gray color you're seeing may be the way your image viewer represents transparency (that's what Preview on Mac does). To get a background color, you'll have to create a full-width rectangle and give it a fill.
