### ISSUE TITLE
Incorrect handling of width/height attribute when the value is in percent (e.g. "100%")

### ISSUE THREAD

**Issue by scardine** [exupero/saveSvgAsPng#42]
Given a SVG tag like:

```
<svg width="100%" ...>...</svg>
```

This code will get the width as 100 pixels instead of the real width:

```
width = parseInt(clone.getAttribute('width') ||
      box.width ||
      clone.style.width ||
      window.getComputedStyle(el).getPropertyValue('width'));
```

Because `parseInt("100%")` is 100. I have a patch enhancing the `options` parameter so you can explicitly give a width/height but I'm not sure this is how you will like to handle this issue.

**Comment by exupero** [comment]
Sounds like it should first check whether `clone.getAttribute('width')` ends with '%' and if so bypass that value and use the box's width.

Something like the following should work:

```
(!clone.getAttribute('width').match(/%$/) && parseInt(clone.getAttribute('width'))) ||
  box.width ||
  clone.style.width ||
  window.getComputedStyle(el).getPropertyValue('width');
```

**Comment by scardine** [comment]
Sounds good. Should I submit a PR?

**Comment by exupero** [comment]
Yes please. Thanks!
