### ISSUE TITLE
svg with viewBox attribute doesn't results in clipped image. 

### ISSUE THREAD

**Issue by cjb06776** [exupero/saveSvgAsPng#43]
With an svg that sets a viewBox, I am seeing the resulting png that gets exported is clipped and only partially rendered in the image.

```
 (for example):  '<svg width="100%" viewBox="0 0 300 225">...</svg>'
```

I played around with the code a little and was able to workaround this with the snippet below:

```
  var viewBoxWidth = el.viewBox.baseVal.width == 0 ? width : el.viewBox.baseVal.width;
  var viewBoxHeight = el.viewBox.baseVal.height == 0 ? height : el.viewBox.baseVal.height;
  clone.setAttribute("viewBox", "0 0 " + viewBoxWidth + " " + viewBoxHeight);
```

I'm not well versed enough with the svg to understand if this is the right way to go about this, although it appears to work in my case.   Would be interested to hear what others think and if you'd consider merging a PR with this patch...

**Comment by exupero** [comment]
I haven't done much with viewboxes, so I'm not sure what the right solution is here. Others will have to weigh in.

A PR to fix this is welcome.

**Comment by cjb06776** [comment]
Created PR https://github.com/exupero/saveSvgAsPng/pull/44
