### ISSUE TITLE
I think this lib doesn't recognize opacity

### ISSUE THREAD

**Issue by thelinuxlich** [exupero/saveSvgAsPng#45]
Trying to export a c3js chart, first I'm creating a rect filled with white color before the chart so it doesn't render it grey, but as you can see, there are these black areas which display as white on the HTML

http://i.imgur.com/YWs0zjL.png

**Comment by thelinuxlich** [comment]
Also the XY axis are much thicker, very strange...

**Comment by sheriferson** [comment]
I use saveSvgAsPng to save some charts I make using d3.js. I found that I have to manually set some styles even if they appear the way I want them to by default in the browser if I want them to also appear that way when exported by saveSvgAsPng. For example I manually set:

```
.style('font-family', 'Fira Sans')
.style('font-size', 12)
```

for I am creating with d3.js even though they already appeared the way I wanted them in the browser. Those `.style` statements made the font styles persist into the exported png. So maybe try setting the axis thickness and area fill colours manually and see if that helps.

**Comment by exupero** [comment]
@thelinuxlich The black areas are caused by the default fill on paths. Set the `fill` attribute or CSS to `none` on those elements and it should solve the problem.

Does the in-browser SVG version of the chart show the black areas, or only the saved image?

If only the saved image shows the black areas, then the save function isn't getting cleared fill style for some reason.

**Comment by Navrot** [comment]
hi,
you have to use selectorRemap option to git rid of black areas and XY axis issue.
for example :

```
saveSvgAsPng(document.getElementById('test'), 'test.png', {
  selectorRemap: function(s) {return s.replace(/.c3 /g, '')}
});
```

Another issue with c3js charts is that the axis labels don't have the good font, which is define in : 

```
.c3 svg {
  font: 10px sans-serif; }
```

But i didn't found a solution for this issue.

(sorry for my english, hope that my answer is still understandable)

**Comment by svemoory** [comment]
Hi,
I have a similar issue with the c3 chart styles where the c3 styles that are included in the rendered chart are not getting translated into the png. Would you be able to provide an example to use selectorRemap and modifyStyle to resolve the issue to get the in-browser styles to the saved png?

thanks.

**Comment by exupero** [comment]
@svemoory Your question is unrelated to this issue. Please open a new issue with example code of what you're trying to do and what you've tried.
