### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by rrag** [exupero/saveSvgAsPng#49]
Thanks for this lib. I am using this for one of my projects. The latest version on npm is 6 months old and there have been a few updates since then on github. I am currently referring to source on github from my `package.json` like

```
"save-svg-as-png": "git://github.com/exupero/saveSvgAsPng.git#gh-pages"
```

Appreciate if you can publish the latest to npm so others do not depend on source from their package.

**Comment by exupero** [comment]
Version 1.0.1 is now available on NPM.

Thanks for the reminder.

**Comment by rrag** [comment]
Thank you
