### ISSUE TITLE
TypeError: el.getBBox is not a function

### ISSUE THREAD

**Issue by linuxorg1** [exupero/saveSvgAsPng#50]
Hi,

I am a newbly in Jscript.
Is this the matter for my Problem?

![svgpng1](https://cloud.githubusercontent.com/assets/12870396/10942019/69e510be-830e-11e5-88f8-9ec0897bd04f.PNG)

**Comment by linuxorg1** [comment]
document.getElementsByTagName('svg')[0].id = 'mysvg';

**Comment by exupero** [comment]
How are you invoking `saveSvgAsPng`?

**Comment by linuxorg1** [comment]
I use this script in 
https://github.com/andredumas/techan.js
after "draw" function, i nvoke saveAsPng
1. ....
        var zoomable = x.zoomable();
        zoomable.domain([indicatorPreRoll, data.length]); // Zoom in a little to hide indicator preroll

```
    draw();

    // Associate the zoom with the scale after a domain has been applied
    zoom.x(zoomable).y(y);
    zoomPercent.y(yPercent);
    saveAsPng(); 
```

....

function saveAsPng() {
        document.getElementsByTagName('svg')[0].id = 'mysvg';
    saveSvgAsPng(document.getElementById("mysvg"), savename);
}

**Comment by exupero** [comment]
`el` is the element passed to `saveSvgAsPng`. Can you confirm that `document.getElementById("mysvg")` returns a node? It sounds like it may be undefined.

**Comment by linuxorg1** [comment]
Hi,
No, this Solution is for me O.K. it funzt.
This line is very importent
document.getElementsByTagName('svg')[0].id = 'mysvg';
I have this Solution from the below link:
http://stackoverflow.com/questions/8027390/how-to-change-or-add-an-id-to-a-svg

document.getElementsByTagName('svg')[0].id = 'svg_id';

That should work if you have only one SVG tag on your page and if you've called it after having created the tag using Raphael.

**Comment by exupero** [comment]
Try the latest version and let me know what error you see.

**Comment by exupero** [comment]
@linuxorg1 I'm closing this as inactive. If it's still a problem, feel free to re-open this.
