### ISSUE TITLE
'window.btoa' fails with characters outside of the Latin1 range

### ISSUE THREAD

**Issue by vivekanandagit** [exupero/saveSvgAsPng#51]
This is happening when i try to convert the d3 charts created by apache zeppelin:

```
Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window':
The string to be encoded contains characters outside of the Latin1 range.
```

**Comment by exupero** [comment]
Do you know what character is causing the problem?

**Comment by miyamotomusashi** [comment]
When using Turkish characters like ö,i,ç,ğ etc. "window.btoa' fails with characters outside of the Latin1 range" issue becomes.

**Comment by exupero** [comment]
Please re-try with the latest.
