### ISSUE TITLE
Possible to save with background colour?

### ISSUE THREAD

**Issue by bradleymarques** [exupero/saveSvgAsPng#52]
Is it possible to save the png images with a specified background colour?  For example, defaulting this to white instead of transparent?

EDIT: I have forked the repo and added this functionality with the existing `options` hash that can be passed into the `saveSvgAsPng()` function.  I have created a pull request for this change.

**Comment by exupero** [comment]
Thanks. This can now be done with the `backgroundColor` option.

**Comment by rompic** [comment]
this doesn't seem to work on edge.

**Comment by exupero** [comment]
I don't have ready access to Edge, so can you attach a screenshot of what the [test page](http://exupero.org/saveSvgAsPng/)'s background color test looks like in Edge?

Here it is in Firefox:
<img width="993" alt="screen shot 2018-03-11 at 8 50 10 am" src="https://user-images.githubusercontent.com/287159/37253534-6a671eca-2509-11e8-9247-8cd99ac3e57e.png">

Also, if it looks different in Edge, could you check for console errors and send those along too?

**Comment by rompic** [comment]
thanks for the fast response. Everything looks good on the test page.
However I noticed, that I set the background to #ffff instead of #ffffff (or #fff).
Everything works as intended.
