### ISSUE TITLE
Fixefox 42.0 SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by rusllonrails** [exupero/saveSvgAsPng#54]
```
SecurityError: The operation is insecure.
var rules = sheets[i].cssRules;
saveSvgAsPng.js (line 59)
```

**Comment by exupero** [comment]
Do you see this error on the [test page](http://exupero.org/saveSvgAsPng/)? Everything seems to be working in Firefox 43.0b1.

Could it be a particular stylesheet causing the problem?

**Comment by rusllonrails** [comment]
@exupero yeah, it works on test page above. 
Looks like issue on my specific stylesheets.
Thanks :beer:

**Comment by exupero** [comment]
Let me know when you find the root cause and I'll add a test case for it.
