### ISSUE TITLE
External stylesheets can be parsed

### ISSUE THREAD

**Issue by mattkolb** [exupero/saveSvgAsPng#57]
if (isExternal(sheets[i].href)) {
        console.warn("Cannot include styles from other hosts: "+sheets[i].href);
        continue;
      }

That code keeps external stylesheets from being parsed. However, if you use the following, they can be parsed. I've tested in Chrome and read reports that say it works in FF as well.
<link href="..."  rel="stylesheet" crossorigin="anonymous">

The key is to make sure the server serving the CSS provides proper cross origin headers. Thankfully, many CDNs for popular libraries do this by default.

**Comment by exupero** [comment]
I've removed the check. If it causes a problem for anyone, file an issue and I'll look into better handling of external stylesheets.
