### ISSUE TITLE
Save fails when the SVG already has an xmlns attribute set

### ISSUE THREAD

**Issue by thaggie** [exupero/saveSvgAsPng#59]
I'm using [highcharts](http://www.highcharts.com/) to render charts and using [saveSvgAsPng](..) to download snapshots, what I've found is that [highcharts](http://www.highcharts.com/) includes a namespace in the markup it produces, this causes [saveSvgAsPng](..) to silently fail.

I've made changes locally to fix this (essentially test to see if the namespace is already set), I can make a pull request if you're interested.

**Comment by exupero** [comment]
A pull request sounds good.

**Comment by exupero** [comment]
Should be fixed by #60. Reopen if the problem persists.
