### ISSUE TITLE
Not working on Firefox too 

### ISSUE THREAD

**Issue by sivagurudurai** [exupero/saveSvgAsPng#61]
Thanks for this Great Script. In chrome it is working nice but In my firefox (version 36) it returns the below error. How to fix it

SecurityError: The operation is insecure.
var rules = sheets[i].cssRules;

**Comment by exupero** [comment]
What external CSS files are you loading?

**Comment by sivagurudurai** [comment]
I am loading 4 .css files and all are loading from same domain.

**Comment by sivagurudurai** [comment]
I have solved this issue!. Just replace var sheets = document.styleSheets; with var sheets = window.document.styleSheets; It is working in both Chrome & Firefox. Thank You.

**Comment by exupero** [comment]
That didn't fix it for me, so I've pushed a change that skips stylesheets that cause that error and gives a warning instead of throwing an error.
