### ISSUE TITLE
Could you bump the version number and update on npm?

### ISSUE THREAD

**Issue by yanofsky** [exupero/saveSvgAsPng#65]
Hi @exupero,

I'm looking to take advantage of the fix for #51, I've tested it manually and it solves a problem on my project mentioned here https://github.com/Quartz/Chartbuilder/issues/194

Could you update the version number to reflect the change and publish to npm so that we can take care of the bug more automatically?

Thank you

**Comment by exupero** [comment]
Done. Thanks.
