### ISSUE TITLE
Custom Fonts - generated png not using custom fonts.

### ISSUE THREAD

**Issue by mtthw** [exupero/saveSvgAsPng#68]
Testing on the sandbox: http://exupero.org/saveSvgAsPng/#custom-font
Is only working for on Linux.

Testing on Linux the png uses the specified font however on Windows and OSx it is defaulting to a serif font.

System information for the Windows test:
Microsoft Windows 10 Pro (10.0.10240)
Firefox: 43.0.1
Chrome: 47.0.2526

Screen shots attached.
![windowsfirefox](https://cloud.githubusercontent.com/assets/1690826/12323013/ee92fd8e-baaf-11e5-8d29-1d30150cdf1f.png)
![windowschrome](https://cloud.githubusercontent.com/assets/1690826/12323008/e8b31a02-baaf-11e5-8310-a612076f6706.png)

**Comment by exupero** [comment]
That's a failing test for #24. Closing as duplicate.

**Comment by mtthw** [comment]
Thanks, didn't realise it was a failing test.
On Linux I have Google fonts installed as system fonts, so it appeared to be functional.

![l inuxfirefox](https://cloud.githubusercontent.com/assets/1690826/12324807/3f1c8736-babd-11e5-9803-4242bed410a1.png)
