### ISSUE TITLE
Doesn't seem to work with foreignObjects

### ISSUE THREAD

**Issue by jrgleason** [exupero/saveSvgAsPng#70]
I tried it on an SVG I generated with D3. All the primitives shapes seemed to come out ok but the foreign objects do not show up. Is there something I can do about this?

**Comment by exupero** [comment]
I haven't seen this problem before and a quick experiment doesn't reproduce it. Can you give an example of your SVG?

**Comment by jrgleason** [comment]
I am seeing a couple other issues too it might be a red herring I will open up issues on the other 2 side effects first then close this one if those fix it.

**Comment by jrgleason** [comment]
Here is a [plunker](1) that demos it.

The UI sucks click on the top button then on the printer if you miss the printer it is hard to tell. But if you hit it you should download the image minus the foreign objects.

**Comment by exupero** [comment]
That doesn't seem to be the right link.

**Comment by jrgleason** [comment]
WTH ok enough crazy markdown tricks then here it is in PT https://plnkr.co/edit/mCPepG4UzPJbO0ghADsr?p=info

**Comment by jrgleason** [comment]
Weird I went to edit it and the address looks correct but you are right that hyperlink is taking you the wrong spot. Make sure to copy paste the text.

**Comment by exupero** [comment]
Try adding `xmlns="http://www.w3.org/1999/xhtml"` to the HTML elements within the `foreignObject`.

**Comment by jrgleason** [comment]
Like every element or just the first on in the FO?

**Comment by jrgleason** [comment]
Looks like that works thanks now on to another issue :-)

**Comment by usmaanalii** [comment]
![screen shot 2018-01-29 at 09 15 51](https://user-images.githubusercontent.com/19881529/35502496-1eeb3700-04d5-11e8-9a21-5c14192227a0.png)

I'm trying to include a div with text, utilising foreign objects,  but they don't show in the resulting image, should this be working?

Using Chrome 63 by the way.

**Comment by exupero** [comment]
There are a couple examples of `foreignObject` working on the [test page](http://exupero.org/saveSvgAsPng/), and they do seem to be working in Chrome 63. One omits the `xmlns` attribute, and the tests it as `xml:xmlns`. It's possible that `contenteditable` breaks rendering of the object to an image, in which case, I'll happily take a pull request that removes that attribute from the cloned SVG tree before exporting it as a PNG.

**Comment by usmaanalii** [comment]
I've tested this in browser (by manually removing `contenteditable`), and it's still missing the foreign object, any other ideas?

**Comment by usmaanalii** [comment]
No worries, found the fix. When you add a `foreignObject`, it must have a `height` attribute, might be worth adding to your documentation, thanks for your help.
