### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by vinnyb0341** [exupero/saveSvgAsPng#78]
Is there a way to get the Png on multiple pages? I am using this with PDFKit and once it writes to canvas only half of what I need is displayed. The rest doesn't appear on the page. If I add more pages, they just appear blank. Any ideas?

**Comment by exupero** [comment]
I doubt there's anything I can do about this. It may be a problem with wkhtmltopdf or not waiting long enough for the JS to complete before rendering to PDF.

wkhtmltopdf should be able to render SVG content, so you shouldn't need to convert SVGs to PNGs before rendering to PDF.

Feel free to open a new issue if you discover something that needs to change in this library.
