### ISSUE TITLE
saveSvgAsPng on specific svg not working

### ISSUE THREAD

**Issue by PjotrC** [exupero/saveSvgAsPng#8]
As I first tried your script, it worked pretty well. But now, after I edited my svg file a lot, it did stop working. Unfortunately there are no error messages. Can I post here a link to the problematic svg or my website?

**Comment by exupero** [comment]
Please do.

**Comment by PjotrC** [comment]
Ok, here is the problematic svg:
https://dl.dropboxusercontent.com/u/17823304/Climograph/Climograph%20Davos.svg

And on that site I've got your script:
https://dl.dropboxusercontent.com/u/17823304/Climograph/Climograph_test.html

**Comment by PjotrC** [comment]
Hi exupero, do you see the problem and can you fix it? Or is there something I can do?
I removed the patterns and clipPaths from my script, that creates the svg, but still it das not work.
These were the things, which I added to, before it stopped working.
Another thing, which differs to my previous SVGs is, that I now use paths with cubic Bézier curves.
I removed them too. And also the indenting, but still its not working.
The only other thing, which I've added are <g> tags - can this be the reason?

**Comment by exupero** [comment]
The problem is caused by the `<br/>` tags within the `<title>` tags. Use the HTML entity `&#013;` instead.

**Comment by PjotrC** [comment]
Ok, I am using that entity now - but still it is not working.

**Comment by exupero** [comment]
Are you using the latest version of the script?

Using the Sandbox on the [test page](http://exupero.org/saveSvgAsPng/), I was able to render the following PNG from your updated SVG code:

![test](https://cloud.githubusercontent.com/assets/287159/3571762/b4895b06-0b60-11e4-8a74-c8c5d858e6ad.png)

**Comment by PjotrC** [comment]
Have you changed something in the last 24h? Anyway, I just downloaded your script again.

Its odd, I tried my new svg (tags replaced with entity) with your index.html demo page and it worked. - But it does not on my page. But it works with my old svg. Please try yourself:
https://dl.dropboxusercontent.com/u/17823304/Climograph/Climograph_old.html (creates the old svg)
https://dl.dropboxusercontent.com/u/17823304/Climograph/Climograph_test.html (creates the new svg)

The code used to call saveSvgAsPng is the same in both versions, the only difference is the svg itself.

Also: After clicking the "save as png file" link, the page seems to be reloaded. You can see this, by changing a value in the table before clicking the link. Afterwards the value is changed back to its initial value (under Chrom - Firefox does remember the user inputs).

**Comment by exupero** [comment]
Your code is saving the contents of the first child of the `#svgContainer` element, which in your new code is an HTML comment. The old SVG lacks the comment and therefore saves fine.

The page reload is due to the link and isn't related to this library. You can change the `href` value to `#` to prevent reloading.

**Comment by PjotrC** [comment]
Arg... I never thought that comments are added to the DOM structure.
Thanks a lot for pointing all this out!

**Comment by exupero** [comment]
I wouldn't have guessed it either. Glad it's working for you.

**Comment by gitfan13** [comment]
@PjotrC I'd live to ask you a few questions about your climate diagrams. Please shoot me a short email at yiyofap@alltempmail.com Thanks!

**Comment by gitfan13** [comment]
@PjotrC I'd live to ask you a few questions about your climate diagrams. Please shoot me a short email, my contacts are at http://mvp2day.com  Thank you!
