### ISSUE TITLE
if svg has some shape out of view; can save these shape into png

### ISSUE THREAD

**Issue by wpfpizicai** [exupero/saveSvgAsPng#82]
I have test the plugin; the result is not satified; Is there any other method to solve this problem.

**Comment by exupero** [comment]
Be more specific. I can't help with so little details on what the problem is.

**Comment by wpfpizicai** [comment]
![2016-04-14 11 03 21](https://cloud.githubusercontent.com/assets/4327513/14515978/4005a75c-0231-11e6-9cbc-84f2dd81cecf.png)
this is the web view ,there is some shape is out of view ;
and below is the result after use saveSvgAsPng API.
![2016-04-14 11 12 17](https://cloud.githubusercontent.com/assets/4327513/14516065/f45a2228-0231-11e6-861f-39d9ceb30eaa.png)

**Comment by wpfpizicai** [comment]
don't care about black node ,It has been resolved; you can see the rightmost node is not complete . I don't know how to make it complete in the result.

**Comment by exupero** [comment]
You can specify the width and height of the output SVG in the options object passed to `saveSvgAsPng` (rather than letting the lib figure it out based on what's rendered to the screen).
