### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by martianov** [exupero/saveSvgAsPng#86]
Hi Eric,
I would like to use **saveSvgAsPng** in my TypeScript project. It requires typings - special bindings for external JS library allowing to access it from TypeScript code. There are two ways to provide typings for JS library: place it inside project or in separate repository. First way is preferred. Some more details you can find by link: https://github.com/typings/typings/issues/322

I suppose **saveSvgAsPng** has quite simple and stable API so it will not be difficult to maintain typings inside package. I've created pull-request with it: #85 
Please let me know what do you think about it. Thanks

**Comment by exupero** [comment]
I recommend you create a separate repo. This project does not depend on TypeScript in any way. I don't want to update this project whenever TypeScript syntax or conventions change, and I won't be able to help anyone who has a question or problem with the TypeScript typings.

If you create a separate repo for TypeScript typings, I will happily accept a pull request to the Readme that tells users where it is.
