### ISSUE TITLE
Svg created programmatically

### ISSUE THREAD

**Issue by gerardp** [exupero/saveSvgAsPng#89]
Hi, i have an svg that is created programmatically, something like this

`var svgstr = '<svg:svg height="300" width="700" id="svg-container"  xmlns="http://www.w3.org/2000/svg"><svg:circle cx="150px" cy="100px" r="30px" /></svg:svg>';`

 how can i call the function to generate the image? this give me an error
`saveSvgAsPng(svgstr, "diagram.png");`

Thanks

**Comment by exupero** [comment]
You must pass a DOM node as the first argument to `saveSvgAsPng`, not a string.
