### ISSUE TITLE
Safari adds 'NS' prefix to attribute names

### ISSUE THREAD

**Issue by adamvmessner** [exupero/saveSvgAsPng#91]
I have a generated SVG that will download fine in Chrome, but I get 

  There was an error loading the data URI as an image

when I attempt the same in Safari. Has anyone else had similar problems with Safari specifically?

**Comment by exupero** [comment]
The latest has some tools to help with this. It should log a URI that you can open in another tab to get the browser's error message.

**Comment by adamvmessner** [comment]
![image](https://cloud.githubusercontent.com/assets/2340281/16275837/69d072a8-3871-11e6-93ee-e7759c5fb854.png)
I'm not seeing a URI in the console anywhere

**Comment by exupero** [comment]
Judging by the line number, that doesn't look like the latest in this repo (https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L237-L241).

**Comment by adamvmessner** [comment]
Ok, I updated, it still gives an error. Unfortunately, the URI is so large it breaks the inspector. I broke it down into a single element and it gives this: 
![image](https://cloud.githubusercontent.com/assets/2340281/16276422/ebba42c4-3873-11e6-88c0-7fd209416a74.png)

**Comment by exupero** [comment]
I can't give you any more help than that error message gives you. You'll have to look at your code to see what it's talking about.

Opening a plain-text SVG file in Safari should show the same error and allow you to tinker with it more easily than SVG code generated by a script.

**Comment by adamvmessner** [comment]
Thanks. I'll post if I find out the problem.

**Comment by adamvmessner** [comment]
Fixed. I added the following to line 201 of the saveSvgAsPng.js file

```
  // Safari xlink NS issue fix
  svg = svg.replace(/NS\d+:href/g, 'xlink:href');
```

**Comment by exupero** [comment]
I'm glad you fixed it, but I'm not familiar with the NS prefix for SVG attribute names. It seems like something that has no business being there in the first place.

**Comment by adamvmessner** [comment]
Yeah, it looks like Safari adds it. I've found some other post about it:

http://stackoverflow.com/questions/30273775/namespace-prefix-ns1-for-href-on-tagelement-is-not-defined-setattributens
