### ISSUE TITLE
Cleanup sometimes skips download

### ISSUE THREAD

**Issue by andrewkkelly** [exupero/saveSvgAsPng#94]
The removeChild call in the download() function sometimes causes the download to be skipped (this only seems to occur after a few attempts, and especially if the image has changed since the last download):

```
  function download(name, uri) {
    var a = document.createElement('a');
    a.download = name;
    a.href = uri;
    document.body.appendChild(a);
    a.addEventListener("click", function(e) {
      a.parentNode.removeChild(a);
    });
    a.click();
  }
```

This slightly modified code seems to work all the time:

```
  function download(name, uri) {
    var a = document.createElement('a');
    a.download = name;
    a.href = uri;
    document.body.appendChild(a);
    a.click();
    a.parentNode.removeChild(a);
  }
```

**Comment by exupero** [comment]
This change appears to break the image download in Firefox, though it does work in Webkit. Can you confirm? Any thoughts as to why?

**Comment by andrewkkelly** [comment]
Firefox works OK for me with the changed code. (I'm using Firefox ESR 45.2.0, and am not permitted to update it).

My understanding (not particularly deep or reliable) is that the `<a>` element needs to be a node in the DOM for the download to work at all in Firefox. This is why the `document.body.appendChild(a);` is required.

When the click event occurs, perhaps (speculating here) Firefox is triggering the event listener before doing the download. so by the time it gets to the download, the `<a>` element is no longer in the DOM.

I don't have a theory about why the original code fails, but it could be something along these lines too. Maybe the events are triggered in a random order, or simultaneously with some sort of race condition.

What if the cleanup code `a.parentNode.removeChild(a);` could be deferred until well after the download is likely to have completed?

**Comment by exupero** [comment]
Thanks. The code does work. I had a transcription error.
